import { MainDecades, SubDecades } from '@shared/types';

export const subDecades: Record<SubDecades, string> = {
  [SubDecades['1700s']]: '1700-е',
  [SubDecades['1720s']]: '1720-е',
  [SubDecades['1730s']]: '1730-е',
  [SubDecades['1740s']]: '1740-е',
  [SubDecades['1750s']]: '1750-е',
  [SubDecades['1760s']]: '1760-е',
  [SubDecades['1790s']]: '1790-е',
  [SubDecades['1800s']]: '1800-е',
  [SubDecades['1810s']]: '1810-е',
  [SubDecades['1820s']]: '1820-е',
  [SubDecades['1830s']]: '1830-е',
  [SubDecades['1840s']]: '1840-е',
  [SubDecades['1850s']]: '1850-е',
  [SubDecades['1860s']]: '1860-е',
  [SubDecades['1870s']]: '1870-е',
  [SubDecades['1880s']]: '1880-е',
  [SubDecades['1890s']]: '1890-е',
  [SubDecades['1900s']]: '1900-е',
  [SubDecades['1910s']]: '1910-е',
  [SubDecades['1920s']]: '1920-е',
  [SubDecades['1930s']]: '1930-е',
  [SubDecades['1940s']]: '1940-е',
  [SubDecades['1950s']]: '1950-е',
  [SubDecades['1960s']]: '1960-е',
  [SubDecades['1970s']]: '1970-е',
  [SubDecades['1980s']]: '1980-е',
  [SubDecades['1990s']]: '1990-е',
  [SubDecades['2000s']]: '2000-е',
  [SubDecades['2010s']]: '2010-е',
  [SubDecades['2020s']]: '2020-е',
  [SubDecades['bc']]: 'До нашей эры',
  [SubDecades['1st_century']]: '1 век',
  [SubDecades['4th_century']]: '4 век',
  [SubDecades['5th_century']]: '5 век',
  [SubDecades['6th_century']]: '6 век',
  [SubDecades['7th_century']]: '7 век',
  [SubDecades['8th_century']]: '8 век',
  [SubDecades['9th_century']]: '9 век',
  [SubDecades['10th_century']]: '10 век',
  [SubDecades['11th_century']]: '11 век',
  [SubDecades['12th_century']]: '12 век',
  [SubDecades['13th_century']]: '13 век',
  [SubDecades['14th_century']]: '14 век',
  [SubDecades['15th_century']]: '15 век',
  [SubDecades['16th_century']]: '16 век',
  [SubDecades['17th_century']]: '17 век',
};
export const decades: Record<MainDecades, { label: string; children?: { value: SubDecades; label: string }[] }> = {
  [MainDecades['21th_century']]: {
    label: '21 век',
    children: [
      { value: SubDecades['2000s'], label: subDecades[SubDecades['2000s']] },
      { value: SubDecades['2010s'], label: subDecades[SubDecades['2010s']] },
      { value: SubDecades['2020s'], label: subDecades[SubDecades['2020s']] },
    ],
  },

  [MainDecades['20th_century']]: {
    label: '20 век',
    children: [
      { value: SubDecades['1900s'], label: subDecades[SubDecades['1900s']] },
      { value: SubDecades['1910s'], label: subDecades[SubDecades['1910s']] },
      { value: SubDecades['1920s'], label: subDecades[SubDecades['1920s']] },
      { value: SubDecades['1930s'], label: subDecades[SubDecades['1930s']] },
      { value: SubDecades['1940s'], label: subDecades[SubDecades['1940s']] },
      { value: SubDecades['1950s'], label: subDecades[SubDecades['1950s']] },
      { value: SubDecades['1960s'], label: subDecades[SubDecades['1960s']] },
      { value: SubDecades['1970s'], label: subDecades[SubDecades['1970s']] },
      { value: SubDecades['1980s'], label: subDecades[SubDecades['1980s']] },
      { value: SubDecades['1990s'], label: subDecades[SubDecades['1990s']] },
    ],
  },

  [MainDecades['19th_century']]: {
    label: '19 век',

    children: [
      { value: SubDecades['1800s'], label: subDecades[SubDecades['1800s']] },
      { value: SubDecades['1810s'], label: subDecades[SubDecades['1810s']] },
      { value: SubDecades['1820s'], label: subDecades[SubDecades['1820s']] },
      { value: SubDecades['1830s'], label: subDecades[SubDecades['1830s']] },
      { value: SubDecades['1840s'], label: subDecades[SubDecades['1840s']] },
      { value: SubDecades['1850s'], label: subDecades[SubDecades['1850s']] },
      { value: SubDecades['1860s'], label: subDecades[SubDecades['1860s']] },
      { value: SubDecades['1870s'], label: subDecades[SubDecades['1870s']] },
      { value: SubDecades['1880s'], label: subDecades[SubDecades['1880s']] },
      { value: SubDecades['1890s'], label: subDecades[SubDecades['1890s']] },
    ],
  },

  [MainDecades['18th_century']]: {
    label: '18 век',
    children: [
      { value: SubDecades['1700s'], label: subDecades[SubDecades['1700s']] },
      { value: SubDecades['1720s'], label: subDecades[SubDecades['1720s']] },
      { value: SubDecades['1730s'], label: subDecades[SubDecades['1730s']] },
      { value: SubDecades['1740s'], label: subDecades[SubDecades['1740s']] },
      { value: SubDecades['1750s'], label: subDecades[SubDecades['1750s']] },
      { value: SubDecades['1760s'], label: subDecades[SubDecades['1760s']] },
      { value: SubDecades['1790s'], label: subDecades[SubDecades['1790s']] },
    ],
  },

  [MainDecades['earlier']]: {
    label: 'Ранее',
    children: [
      { value: SubDecades['bc'], label: subDecades[SubDecades['bc']] },
      { value: SubDecades['1st_century'], label: subDecades[SubDecades['1st_century']] },
      { value: SubDecades['4th_century'], label: subDecades[SubDecades['4th_century']] },
      { value: SubDecades['5th_century'], label: subDecades[SubDecades['5th_century']] },
      { value: SubDecades['6th_century'], label: subDecades[SubDecades['6th_century']] },
      { value: SubDecades['7th_century'], label: subDecades[SubDecades['7th_century']] },
      { value: SubDecades['8th_century'], label: subDecades[SubDecades['8th_century']] },
      { value: SubDecades['9th_century'], label: subDecades[SubDecades['9th_century']] },
      { value: SubDecades['10th_century'], label: subDecades[SubDecades['10th_century']] },
      { value: SubDecades['11th_century'], label: subDecades[SubDecades['11th_century']] },
      { value: SubDecades['12th_century'], label: subDecades[SubDecades['12th_century']] },
      { value: SubDecades['13th_century'], label: subDecades[SubDecades['13th_century']] },
      { value: SubDecades['14th_century'], label: subDecades[SubDecades['14th_century']] },
      { value: SubDecades['15th_century'], label: subDecades[SubDecades['15th_century']] },
      { value: SubDecades['16th_century'], label: subDecades[SubDecades['16th_century']] },
      { value: SubDecades['17th_century'], label: subDecades[SubDecades['17th_century']] },
    ],
  },

  [MainDecades['unknown']]: {
    label: 'Другие',
  },
};
