export enum MainDecades {
  'unknown',
  'earlier',
  '18th_century',
  '19th_century',
  '20th_century',
  '21th_century',
}

export enum SubDecades {
  '1700s',
  '1720s',
  '1730s',
  '1740s',
  '1750s',
  '1760s',
  '1790s',
  '1800s',
  '1810s',
  '1820s',
  '1830s',
  '1840s',
  '1850s',
  '1860s',
  '1870s',
  '1880s',
  '1890s',
  '1900s',
  '1910s',
  '1920s',
  '1930s',
  '1940s',
  '1950s',
  '1960s',
  '1970s',
  '1980s',
  '1990s',
  '2000s',
  '2010s',
  '2020s',
  'bc',
  '1st_century',
  '4th_century',
  '5th_century',
  '7th_century',
  '8th_century',
  '6th_century',
  '9th_century',
  '10th_century',
  '11th_century',
  '12th_century',
  '13th_century',
  '14th_century',
  '15th_century',
  '16th_century',
  '17th_century',
}

export const subDecades: Record<SubDecades, string> = {
  [SubDecades['1700s']]: '-е',
  [SubDecades['1720s']]: '-е',
  [SubDecades['1730s']]: '-е',
  [SubDecades['1740s']]: '-е',
  [SubDecades['1750s']]: '-е',
  [SubDecades['1760s']]: '-е',
  [SubDecades['1790s']]: '-е',
  [SubDecades['1800s']]: '-е',
  [SubDecades['1810s']]: '-е',
  [SubDecades['1820s']]: '-е',
  [SubDecades['1830s']]: '-е',
  [SubDecades['1840s']]: '-е',
  [SubDecades['1850s']]: '-е',
  [SubDecades['1860s']]: '-е',
  [SubDecades['1870s']]: '-е',
  [SubDecades['1880s']]: '-е',
  [SubDecades['1890s']]: '-е',
  [SubDecades['1900s']]: '-е',
  [SubDecades['1910s']]: '-е',
  [SubDecades['1920s']]: '-е',
  [SubDecades['1930s']]: '-е',
  [SubDecades['1940s']]: '-е',
  [SubDecades['1950s']]: '-е',
  [SubDecades['1960s']]: '-е',
  [SubDecades['1970s']]: '-е',
  [SubDecades['1980s']]: '-е',
  [SubDecades['1990s']]: '-е',
  [SubDecades['2000s']]: '-е',
  [SubDecades['2010s']]: '-е',
  [SubDecades['2020s']]: '-е',
  [SubDecades['bc']]: '',
  [SubDecades['1st_century']]: ' век',
  [SubDecades['4th_century']]: ' век',
  [SubDecades['5th_century']]: ' век',
  [SubDecades['7th_century']]: ' век',
  [SubDecades['8th_century']]: ' век',
  [SubDecades['6th_century']]: ' век',
  [SubDecades['9th_century']]: ' век',
  [SubDecades['10th_century']]: ' век',
  [SubDecades['11th_century']]: ' век',
  [SubDecades['12th_century']]: ' век',
  [SubDecades['13th_century']]: ' век',
  [SubDecades['14th_century']]: ' век',
  [SubDecades['15th_century']]: ' век',
  [SubDecades['16th_century']]: ' век',
  [SubDecades['17th_century']]: '17 век',
};
export const decades: Record<MainDecades, { label: string; children: { value: SubDecades; label: string }[] }> = {
  [MainDecades['21th_century']]: {
    label: '21 век',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades['20th_century']]: {
    label: '20 век',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades['19th_century']]: {
    label: '19 век',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades['18th_century']]: {
    label: '18 век',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades['earlier']]: {
    label: '0-17 века',
    children: [
      { value: SubDecades['6th_century'], label: '6 век' },
      { value: SubDecades['7th_century'], label: '7 век' },
      { value: SubDecades['8th_century'], label: '8 век' },
      { value: SubDecades['9th_century'], label: '9 век' },
      { value: SubDecades['10th_century'], label: '10 век' },
      { value: SubDecades['11th_century'], label: '11 век' },
      { value: SubDecades['12th_century'], label: '12 век' },
      { value: SubDecades['13th_century'], label: '13 век' },
      { value: SubDecades['14th_century'], label: '14 век' },
      { value: SubDecades['15th_century'], label: '15 век' },
      { value: SubDecades['16th_century'], label: '16 век' },
      { value: SubDecades['17th_century'], label: '17 век' },
    ],
  },

  [MainDecades['unknown']]: {
    label: 'Другие',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades.bc]: {
    label: '',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },

  [MainDecades.bc]: {
    label: '',
    children: [
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
      { value: SubDecades, label: '' },
    ],
  },
};
