import type { AestheticProps } from '@shared/types';

export const americana: AestheticProps[] = [
  {
    url: 'https://aesthetics.fandom.com/wiki/Western',
    name: 'Western',
    id: 'western',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/03/Shadow-rider.jpg',
    description:
      'CottagecoreCountryDesertGauchoPrairieRusticcore Western, also known as the Wild West, is a literary genre inspired by the lives of early settlers of the American Frontier. The Western aesthetic entails themes of self-reliance, solitude, and wildness. Western folklore often includes tales of lone vigilantes travelling the American Frontier on horseback, more times than not armed with a six-shooter revolver or a rifle and prepared to dole out justice. Visually, the Western aesthetic shares many similarities to that of Country, but places an emphasis on imagery of the historical Wild West, as well as the motifs of vigilantism and adventure commonly depicted in popular Western films. While the Country aesthetic romanticizes the life of family, farming, and living in the countryside, Western focuses more on the idea of the wilderness, specifically the desert and prairie, as well as wandering town to lawless town dotted across the American Frontier.',
    categories: ['genre_fiction', 'historical', 'music', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Cowboy', 'Cowgirl', 'Wild West', 'Wild Wild West', 'Old West', 'Bang Bang', 'Spaghetti Western'],
        decade: ['19th_century', '1860s'],
        creator: ['The Settlers of the American Frontier'],
      },
      visualThemes: {
        motifs: ['Cowboy hats', 'Horses', 'Cacti', 'Revolvers', 'Leather clothing'],
        colours: ['Muted tones', 'Browns', 'Red', 'Orange'],
        values: ['Remembrance', 'Pioneering spirit', 'Independence'],
      },
      connections: {
        related: ['americana', 'cottagecore', 'country', 'desert', 'gaucho', 'prairie', 'rusticcore'],
        overlaped: ['victorian'],
      },
      mediaCulture: {
        media: ['Red Dead Redemption', 'Old Western films'],
      },
      timeline: {
        preceded: ['american_pioneers'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Diner',
    name: 'Diner',
    id: 'diner',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/a/a1/Diner_moodb.png',
    description:
      'While the diner is a stop for travel, it also provides comfort to the locals and facilitates new encounters with kind strangers. Its owners and employees are typically the paragon of American homey stereotypes: hard-working blue collar people who want to make a living and enjoy life in their independent restaurant. Diners also evoke comfort in Americans because of the comfort food they serve. The diner is a significant place in fiction because of this. Media, especially centered around high school students or wanderers, typically uses diners as meeting places or encounters with new characters. There are mainly 2 types of ways this aesthetic is utilized. One is the traditional, and the other is modern. The traditional version uses warmer colors and generally sticks closer to historical accuracy, with little-to-no use of over-the-top tropes and kitsch. The modern version is as it sounds--a modern take on the 1950s diners, transforming it with brighter colors, sometimes neon and glowing. Many modern businesses also try to capitalize on the novelty and clutter the restaurant with paraphernalia that reminds the diners of the 1950s.',
    categories: ['lifestyle', 'location_based_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['20th_century', '1950s'],
      },
      visualThemes: {
        colours: ['Any colors.'],
      },
      connections: {
        related: [
          'americana',
          'diner_kitsch_revivalgoogie_kitsch',
          'foodie',
          'googie',
          'mid-century_modern',
          'atompunk',
          'raygun_gothic',
          'paninaro',
          'vaporwave',
          'vintage_americana',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Rockabilly',
    name: 'Rockabilly',
    id: 'rockabilly',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/c/c5/Rockabilly_002.jpg',
    description:
      'BikerBurlesqueCountryDinerGreaserHalbstarkeHorror PunkHot RodOld HollywoodPin-upRaggareStilyagi The rockabilly subculture also encompasses a distinct aesthetic rooted in 1950s Americana. This visual style often includes elements like vintage cars, motorcycles, and imagery associated with diners and soda fountains. Fashion commonly features wide dresses, tight jeans, leather jackets, and specific hairstyles such as men\'s slicked-back "greaser" dos and women\'s pinned-up hair. The color palette frequently incorporates white, red, and black. While drawing from 1950s styles, the aesthetic can also include modern elements like tattoos and piercings. While its initial widespread popularity declined in the late 1950s, rockabilly experienced a revival in the late 1970s and early 1980s. The subculture continues to exist in the 21st century, with enthusiasts often embracing a lifestyle and fashion inspired by 1950s rock and roll, sometimes exhibiting exaggerated motifs of that era. Rockabilly has influenced other genres, including punk rock, and has spawned various sub-styles, such as Psychobilly and Gothabilly.',
    categories: ['music_genres', 'subcultures', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Rockabella (feminine)'],
        decade: ['20th_century', '1950s', '1970s'],
        creator: ['Carl Perkins', 'Elvis Presley', 'Johnny Burnette', 'Jerry Lee Lewis (early influential artists)'],
      },
      visualThemes: {
        motifs: [
          'Vintage cars',
          'motorcycles',
          'diners',
          'soda fountains',
          'jukeboxes',
          'polka dots',
          'checkerboard patterns',
          'skulls',
          'old-school tattoos',
          'pin-up imagery',
          'red roses',
          'poodles',
          'barber poles',
        ],
        colours: ['White', 'red', 'black', 'bright pastels'],
        values: [
          'Nostalgia for 1950s Americana',
          'rebellion',
          'individualism',
          'authenticity',
          'passion for music and vintage culture',
        ],
      },
      connections: {
        related: [
          'americana',
          'biker',
          'burlesque',
          'country',
          'diner',
          'greaser',
          'halbstarke',
          'horror_punk',
          'hot_rod',
          'old_hollywood',
          'pin-up',
          'raggare',
          'stilyagi',
        ],
        subgenres: ['gothabilly', 'psychobilly'],
      },
      mediaCulture: {
        media: ['American Graffiti', 'Cry-Baby', 'Grease'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Greaser',
    name: 'Greaser',
    id: 'greaser',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/d/db/Hi39ipxqow.jpg',
    description:
      'In the 1950s and 1960s, these youths were also known as "hoods". This may be due to the fact that the style was more popular in poor neighborhoods that had higher crime rates than upper-class neighborhoods. Greasers grew out of post–World War II social and economic conditions, particularly among working-class and lower-income youths in urban neighborhoods. Many came from Italian American, Mexican American, and other Latino backgrounds, and the subculture expressed frustration with a conformist, middle-class 1950s society that they felt excluded them.[1][2][3][4] The name "greaser" came from the greased-back hairstyles these people wore (which involved combing back hair using hair wax, hair gel, creams, tonics or pomade), though it also originally functioned as a slur, tied to earlier racist usage against Mexican laborers in 19th‑century California. By the 1950s it became associated with urban “hoods” or “toughs,” and middle-class Americans often viewed greasers as threatening or delinquent even as they were also romanticized as exciting outsiders.[5][6][2][3][4]',
    categories: ['fashion'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['20th_century', '1950s'],
      },
      visualThemes: {
        motifs: [
          'Pompadour hair',
          'leather jackets or jean jackets',
          'T-shirts',
          'cuffed-up pants or denim pants',
          'boots',
          'feminine scarf',
          'sunglasses',
          'delinquency',
          'youth',
          'cigarettes',
          'switchblades',
          'souped-up cars',
          'motorcycles',
        ],
        colours: ['Black', 'white', 'red'],
        values: [
          'Freedom',
          'enjoying life',
          'chilling out with friends',
          'self-defense',
          'bravery',
          'gang loyalty',
          'family',
          'rejection of societal norms or mainstream culture',
          'anti-capitalism',
          'democratic socialism/anarchism',
        ],
      },
      connections: {
        related: ['americana', 'bobby-soxer', 'guido', 'halbstarke', 'old_hollywood', 'punk', 'raggare', 'rockabilly'],
      },
      mediaCulture: {
        media: ['Cry-Baby', 'Grease', 'The Outsiders'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Vintage_Americana',
    name: 'Vintage Americana',
    id: 'vintage_americana',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/e/e6/A6c83efcc74d5f83d4683045c6a2beeb.jpg',
    description:
      "Vintage Americana emerged in the early 2010s as a distinct aesthetic, primarily driven by online communities and popular culture. It draws inspiration from an idealized representation of American life, fashion, and culture spanning the 1950s through the 1980s. This aesthetic is rooted in nostalgia for a perceived simpler past, using elements of Old Hollywood glamour, mid-century girlhood, and iconic Americana imagery. The aesthetic's surge in popularity is atrributed to the artist Lana Del Rey, particularly with her debut EP and subsequent album Born to Die released in 2012. Del Rey's musical output, alongside her visual presentation in music videos and public appearances, consistently showed motifs such as vintage cars, American flags, classic diners, and a melancholy romanticization of American landscapes and lifestyles. Her artistic persona, influenced by figures such as Priscilla Presley and Nancy Sinatra, framed modern experiences through a sepia-toned, retro lens. The Vintage Americana aesthetic often overlaps with other styles such as Coquette and Nymphet. This connection stems from a shared emphasis on hyper-femininity, a romanticized view of youth, and an innocent yet sometimes suggestive allure that harks back to mid-century gender roles and pop culture archetypes, including those referenced in works like Nabokov's Lolita. While Lana Del Rey's personal style evolved, her music remained a central inspiration for the Coquette aesthetic's core ethos of escapism through nostalgia, often evoking the perceived homogeneity and \"American Dream\" ideals of the 1950s and 1960s.",
    categories: ['cultural_nostalgia', 'internet_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['21th_century', '2010s'],
        location: ['United States'],
      },
      visualThemes: {
        motifs: [
          'Vintage diners',
          'vintage cars',
          'hearts',
          'gingham',
          'cherry print',
          'Old Hollywood imagery',
          'mid-century American pop culture',
          'pin-up aesthetics',
          'road trips',
          'desolate desert landscapes',
        ],
        colours: ['Red', 'white', 'and blue; pastel tones'],
        values: [
          'Nostalgia for an idealized American past',
          'romanticized femininity',
          'escapism',
          'hedonism',
          'perceived innocence of mid-century girlhood',
          'American patriotism of a bygone era',
        ],
      },
      connections: {
        related: [
          '50s_suburbia',
          'americana',
          'coquette',
          'diner',
          'hot_rod',
          'nymphet',
          'pin-up',
          'rockabilly',
          'trailer_park_princess',
        ],
      },
      mediaCulture: {
        media: [
          "Lana Del Rey's music videos (National Anthem, Ride)",
          'Music (Lana Del Rey',
          'MARINA',
          'Elvis Presley)',
          'Films depicting idealized 1950s/60s Americana (e.g.',
          '"Lolita" (1997) for Nymphet connections)',
        ],
        brands: ['Coca-Cola (as an iconic motif)', 'Budweiser (as a motif)'],
        figures: [
          'Lana Del Rey; Priscilla Presley; Nancy Sinatra; Classic Hollywood stars (e.g.',
          'James Dean for denim influence); Betty Page (for pin-up influence)',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/50s_Suburbia',
    name: '50s Suburbia',
    id: '50s_suburbia',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/0a/3784db89ff468d64b1e7539b760c713d.jpg',
    description:
      'The 50s Suburbia aesthetic is the idealized vision of American middle-class life that became a dominant cultural force in the post-World War II era. \n      Fueled by an economic boom and the mass production of tract housing in developments like Levittown, this aesthetic is centered on the concept of \n      the nuclear family and its life in a homogeneous, newly built suburban community. The aesthetic is defined by manicured lawns, single-family homes, and large \n      American automobiles, while the ideology is rooted in conformity, consumerism, and strict traditional gender roles: the male breadwinner commuting to his white-collar job \n      and the cheerful, domestic housewife.',
    categories: ['architectural_styles', 'cultural_nostalgia', 'historical', 'location_based_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['The American Dream', 'Mid-Century Suburbia'],
        decade: ['20th_century', '1950s'],
        location: ['United States'],
      },
      visualThemes: {
        motifs: [
          'nuclear family',
          'manicured lawns',
          'picket fences',
          'station wagons',
          'Tupperware parties',
          'backyard barbecues',
          'new household appliances',
        ],
        colours: ['pastels', 'mint green', 'baby pink', 'powder blue', 'cherry red', 'turquoise', 'white'],
        values: [
          'conformity',
          'traditional gender roles',
          'consumerism',
          'family',
          'community',
          'optimism',
          '"keeping up with the Joneses"',
        ],
      },
      connections: {
        related: [
          'americana',
          'googie',
          'mid-century_modern',
          'space_age',
          'suburban_gothic',
          'tradwife',
          'vintage_americana',
        ],
      },
      mediaCulture: {
        media: ['Leave It to Beaver', 'The Donna Reed Show', 'I Love Lucy', 'Pleasantville'],
        brands: ['Chevrolet', 'Cadillac', 'Ford', 'Coca-Cola', 'Tupperware', 'Pyrex'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Route_66',
    name: 'Route 66',
    id: 'route_66',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/e/e6/3afff5be1b752e16e607d5b4f0188288.jpg',
    description:
      'DinerGoogieGreaserHot RodMid-Century ModernRockabilly The aesthetic often overlaps with Greaser culture and the broader Hot Rod/Kustom Kulture, utilizing motifs like classic cars and "greasy spoon" diners. The aesthetic romanticizes the period when the Mother Road was the symbol of westward expansion and the American Dream; the promise of a better life in California, particularly for Dust Bowl migrants (cemented by The Grapes of Wrath). Today, its appeal is not necessarily based on genuine nostalgia, but rather the appreciation of kitsch—the visible, commodified imitation of a simpler past, which has itself become a unique modern tourist attraction.[2]',
    categories: ['architectural_styles'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: [
          'Route 66 Kitsch',
          'Mid-Century Roadside Americana',
          'Mother Road Aesthetic',
          'Radiator Springs (pop-culture reference)',
        ],
        decade: ['20th_century', '1950s'],
        location: ['U.S. Route 66 (Illinois to California)'],
      },
      visualThemes: {
        motifs: [
          'Googie architecture',
          'Programmatic/Mimetic Architecture (buildings shaped like products/animals)',
          'oversized "Muffler Men" statues',
          'mid-century neon signage',
          'chrome',
          'dry desert scenery',
          'vintage gas stations',
          'classic American cars (tail fins)',
        ],
        colours: ['Desert Palette (dusty earth tones)', 'neon', 'chrome silver', 'pastel pink/blue/mint'],
        values: [
          'Freedom',
          'mobility',
          'technological optimism (post-WWII)',
          'autotourism',
          'nostalgia for the American Dream',
          'kitsch',
        ],
      },
      connections: {
        related: ['americana', 'diner', 'googie', 'greaser', 'hot_rod', 'mid-century_modern', 'rockabilly'],
      },
      mediaCulture: {
        media: ['American Graffiti (1973)', "Pixar's CARS (2006)", "Nat King Cole's Route 66 (song)"],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Pin-up',
    name: 'Pin-up',
    id: 'pin-up',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/a/a9/Pearlart10.jpg',
    description:
      'Pin-up refers to a model whose mass-produced images see wide appeal as popular culture. The aesthetic is characterized by a playful and glamorous portrayal of sexuality, often with a nostalgic, mid-20th-century feel. Although the term "pin-up" was not coined until 1941, its origins can be traced to earlier forms of glamour art and photography. The style is most associated with female models, often called "cheesecake," but also includes male models, known as "beefcake." Pin-up images are intended to be "pinned up" on a wall and typically feature models in alluring, often romanticized poses. The aesthetic ranges from innocent and playful to more explicitly suggestive and fetish-oriented themes. In modern times, the pin-up style has been embraced as a form of empowerment, celebrating confidence, beauty, and ownership of one\'s sexuality, famously embodied by figures like Marilyn Monroe and Bettie Page. The modern pin-up aesthetic began to take shape in the 1920s and 30s, evolving from early burlesque advertisements and the illustrative work of artists like Alberto Vargas, whose idealized paintings of women became known as "Vargas Girls." During this period, Black bombshells like Josephine Baker and Dorothy Dandridge also became influential figures, carving out their own space in the glamour and entertainment industries.',
    categories: ['fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Cheesecake (female)', 'Beefcake (male)', 'Glamour modeling'],
        decade: ['20th_century', '1920s'],
        location: ['United States'],
      },
      visualThemes: {
        motifs: [
          'Red lipstick',
          'victory rolls',
          'high-waisted shorts',
          'polka-dots',
          'leopard print',
          'lingerie',
          'swimsuits',
          'garter belts',
          'stockings',
        ],
        colours: ['Red', 'black', 'white', 'navy blue', 'pastels'],
        values: ['Sexuality', 'confidence', 'glamour', 'nostalgia', 'empowerment', 'playful charm'],
      },
      connections: {
        related: [
          'atompunk',
          'burlesque',
          'femme_fatale',
          'gibson_girl',
          'gothabilly',
          'greaser',
          'psychobilly',
          'rockabilly',
          'stilyagi',
        ],
      },
      mediaCulture: {
        brands: ['Playboy'],
        figures: ['Bettie Page', 'Marilyn Monroe', 'Betty Grable', 'Alberto Vargas', 'Dita Von Teese'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Hot_Rod',
    name: 'Hot Rod',
    id: 'hot_rod',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/f/fb/Hot_rod_pci8hi.jpg',
    description:
      'Hot rodding began as a functional pursuit of speed in the 1930s, utilizing dry lake beds for racing. The National Hot Rod Association (NHRA) was established in 1951 to formalize drag racing, while the Southern California Timing Association (SCTA) managed dry lake events. Publications such as Hot Rod Magazine, founded in 1948, documented and standardized the mechanical and visual trends of the subculture across the United States. The Hot Rod aesthetic stems from structural modifications made to pre-war vehicles to reduce weight and improve aerodynamics. The 1932 Ford (Model B), commonly referred to as the "Deuce Coupe," along with early Ford Model Ts and Model As, serve as the primary foundational vehicles. Structural changes include the removal of fenders, hoods, and bumpers. Rooflines are frequently "chopped" (lowered) to decrease drag, and the vehicle body is often "channeled" (lowered over the frame rails) to reduce ground clearance. The removal of the hood leaves the engine, frequently a Ford flathead V8 or a small-block Chevy V8, completely exposed.',
    categories: ['subcultures'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Hot Rodding', 'Hot Rod Culture'],
        decade: ['20th_century', '1930s'],
        location: ['Southern California', 'United States'],
        creator: ['Early automotive enthusiasts and returning WWII veterans'],
      },
      visualThemes: {
        motifs: [
          'Stripped-down pre-1949 Fords (Model Ts',
          'Model As',
          "'32 Deuce Coupe)",
          'exposed engines',
          'chopped roofs',
          'pinstriping',
          'flames',
          'chrome',
          'dry lake racing',
          'drag racing',
        ],
        colours: ['Chrome', 'deep glossy lacquer colors (red', 'black', 'yellow)', 'primer/matte black (Rat Rods)'],
        values: [
          'Speed',
          'technical innovation',
          'anti-conformity',
          'self-expression',
          'hands-on craftsmanship',
          'Americana',
        ],
      },
      connections: {
        related: ['americana', 'greaser', 'kustom_kulture', 'pin-up', 'raggare', 'rockabilly', 'route_66'],
      },
      mediaCulture: {
        platform: ['Dry lake beds', 'drag strips', 'car shows', 'Hot Rod Magazine'],
      },
      timeline: {},
    },
  },
];
