import type { AestheticProps } from '@shared/types';

export const grunge: AestheticProps[] = [
  {
    url: 'https://aesthetics.fandom.com/wiki/Corporate_Grunge',
    name: 'Corporate Grunge',
    id: 'corporate_grunge',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/d/df/Corporate_Grunge_52.png',
    description:
      'Rad Dog/Neon Surf ShackEarly Cyber VectordeliaMcBlingUrBling As grunge began to take hold in the mainstream, companies were quick to mass market the aesthetics and motifs often used within the grunge genre, such as working class fashion heavily rooted in Seattle, distressed typeface, collage imagery and industrial decay. The authenticity of the genre was stripped to market the young demographic within Generation X.',
    categories: ['consumer_aesthetics', 'design_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Grunge™', 'Neugrunge'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'Rough textures',
          'typewriter fonts',
          'distressed font',
          'label makers',
          'grainy overlays',
          'industrial decay',
          'collage imagery',
          'glitch & VHS artifacts',
        ],
        colours: ['Soot black', 'paper beige', 'sepia brown', 'muddy earth tones'],
        values: ['Controlled rebellion', 'dilution', 'anti-consumerist aesthetic'],
      },
      connections: {
        related: [
          'corporate_gen-x_cyber',
          'early_cyber',
          'cyberpunk',
          'gen_x_soft_club',
          'grunge',
          'industrial',
          'sepia_blur',
          'teenpunk',
          'ur',
          'bling',
          'horror-grunge',
          'metalheart',
          'cyberdelic',
          'raver',
          'rivethead',
          'industrial',
          'mission_school',
          'nu-metal',
          'y2k_futurism',
          'alternative',
          'memphis_design',
        ],
        subgenres: ['early_cyber', 'corporate_gen-x_cyber', 'grunge', 'sepia_blur', 'cyberdelic'],
      },
      mediaCulture: {
        media: ['Se7en', 'My So-Called Life', 'WWF Attitude', 'The Craft', 'RENT'],
        brands: [
          'West 49',
          'Play',
          'Station',
          'Mr. Rags',
          'Perry Ellis (Marc Jacobs)',
          'Pog',
          'Quicksilver',
          'No Fear',
          'GAP ATHLETIC',
          'JCPenny',
        ],
      },
      timeline: {
        preceded: ['memphis_design', 'rad_dog/neon surf shack', 'early_cyber'],
        succeeded: ['frutiger_aero', 'vectordelia', 'mcbling', 'ur', 'bling'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Cyber_Grunge',
    name: 'Cyber Grunge',
    id: 'cyber_grunge',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/1/10/Cfg_military.jpg',
    description:
      'Cyber Grunge is an aesthetic that blends elements of Grunge, streetwear, and Y2K Futurism, sometimes with slight military influences. This style, which has been observed since approximately 2022, is characterized by bold silhouettes, utilitarian features, and an infusion of futuristic elements. It largely utilizes "subversive basics," referring to simple clothing with alternative or avant-garde details such as cut-outs, mesh, and pockets. The influence of the Y2K revival is also prevalent, with accessories, prints, and silhouettes from that era being common. Cyber Grunge seamlessly blends elements of rebellion, urban edge, and a touch of Y2K nostalgia. The fashion style borrows from the concept of "subversive basics" and the preference for the earthy, muted color palette often associated with Grunge, including browns, greens, and greys. An utilization of layered androgynous clothing with a mix of oversized and distressed items are characteristic for Cyber Grunge. Wearing large headphones, goggles, or other futuristic accessories enhance the overall look. 90s Cool ◉ Bubblegum Dance ◉ Chromecore ◉ Cyber Grunge ◉ Cyber Stylin\' ◉ FantasY2K ◉ Four Colors ◉ Gen X Soft Club ◉ Low Poly ◉ McBling ◉ Metalheart ◉ Shibuya Punk ◉ Surf Crush ◉ Teenpunk ◉ UrBling ◉ Vectorheart ◉ Webcore ◉ Y2K Futurism',
    categories: ['fashion_styles'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Y2K Grunge', 'Military Y2K'],
        decade: ['21th_century', '2020s'],
      },
      visualThemes: {
        motifs: [
          'Distressed clothing',
          'utilitarian details (pockets',
          'straps)',
          'Y2K silhouettes',
          'layered androgynous clothing',
          'dark color palette',
          '(variations: military influences',
          'urban decay)',
        ],
        colours: ['Black', 'gray', 'muted greens', 'browns', 'and blues'],
        values: [
          'Urban edge',
          'rebellious style',
          'Y2K nostalgia',
          'utilitarianism',
          'societal critique',
          'disillusionment',
        ],
      },
      connections: {
        related: [
          'acubi',
          'avant_apocalypse',
          'denpa',
          'fairy_grunge',
          'gen_x_soft_club',
          'goblincore',
          'grunge',
          'industrial_decay',
          'mallgoth',
          'opium',
          'post-grunge_maximalism',
          'stargirl',
          'twilightcore',
          'urbancore',
          'y2k_futurism',
        ],
      },
      mediaCulture: {
        media: ['Serial Experiments Lain', '90s/2000s alternative music', 'urban photography'],
        brands: ['Fruits'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Fairy_Grunge',
    name: 'Fairy Grunge',
    id: 'fairy_grunge',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/8/8b/Fairy_grunge_mb.png',
    description:
      'The Iron Fey series by Julie KagawaBratz Fashion PixiezWinx ClubW. I. T. C. H.Labyrinth BeabadoobeeHolly BlackStevie NicksKatie Jane GarsideThe Pixies GrungeCottagecoreMori KeiFairycoreKinderwhore',
    categories: ['fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Grunge Fairycore', 'Grunge Fairy'],
        decade: ['21th_century', '2020s'],
      },
      visualThemes: {
        motifs: ['Dark clothing', 'moss', 'crystals', 'fairies', 'forests'],
        colours: ['brown', 'black', 'green', 'earthy tones'],
        values: ['Nature', 'escapism', 'individualism', 'creativity', 'rebellion'],
      },
      connections: {
        related: [
          'avant_apocalypse',
          'cottagecore',
          'cyber_grunge',
          'fairycore',
          'fantas',
          'y2kfemale_horror_game_protagonist_fashion',
          'goblincore',
          'grunge',
          'kinderwhore',
          'mori_kei',
          'mythpunk',
          'strega',
          'winter_bimbo',
          'twilightcore',
        ],
        subgenres: ['fairy_hippie'],
      },
      mediaCulture: {
        platform: ['Tik', 'Tok', 'Tumblr', 'Pinterest'],
        media: [
          'Modern Faerie Tales trilogy by Holly Black',
          'The Iron Fey series by Julie Kagawa',
          'Bratz Fashion Pixiez',
          'Winx Club',
          'W. I. T. C. H.Labyrinth',
        ],
        figures: ['Florence Welch', 'Beabadoobee', 'Holly Black', 'Stevie Nicks', 'Katie Jane Garside', 'The Pixies'],
      },
      timeline: {
        preceded: ['goblincore', 'grunge', 'cottagecore', 'mori_kei', 'fairycore', 'kinderwhore'],
        succeeded: ['fairy_hippie', 'elf_punk', 'japanese_horror game protagonist fashion'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Grunge',
    name: 'Grunge',
    id: 'grunge',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/4/47/Grunge_moodb.png',
    description:
      "Grunge is an alternative rock genre and associated subculture that emerged from Seattle, Washington in the mid-late 1980s and achieved mainstream popularity in the early-mid 1990s. As the definitive sound of Generation X, it was a reaction against the glamorous excess of 1980s glam metal, fusing the raw energy of punk with the sludgy, heavy riffs of early heavy metal. The music, also known as the \"Seattle sound,\" was pioneered by bands like Nirvana, Pearl Jam, Soundgarden, and Alice in Chains, and is defined by its distorted guitars and angst-filled lyrics with themes of social alienation, apathy, and confinement.[1] The associated fashion was a utilitarian, anti-consumerist statement rooted in the Pacific Northwest's working-class culture, consisting of thrifted items like oversized flannel shirts, ripped jeans, band t-shirts, and combat boots. The movement's mainstream popularity was short-lived, largely ending with the breakup of Soundgarden in 1997, but its influence on alternative music and fashion has been profound and long-lasting. The origins of Grunge lie in the Pacific Northwest's underground music scene of the mid-1980s, centered on the independent record label Sub Pop. Early bands like Green River, Bam Bam, The Melvins, and Mudhoney were instrumental in developing the genre's sound by blending the DIY ethos of punk with the slower, heavier sound of bands like Black Sabbath. This created a raw, unpolished, and emotionally intense style of rock that stood in stark contrast to the slickly produced music dominating the mainstream charts.",
    categories: ['music_genres', 'subcultures', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Seattle Sound'],
        decade: ['20th_century', '1980s'],
        location: ['Seattle', 'Washington', 'USA'],
      },
      visualThemes: {
        motifs: [
          'Flannel shirts',
          'ripped jeans',
          'band t-shirts',
          'Doc Martens',
          'oversized sweaters',
          'long unkempt hair',
        ],
        colours: ['Earthy and muted tones: brown', 'army green', 'grey', 'burgundy', 'faded denim'],
        values: ['Anti-consumerism', 'authenticity', 'apathy', 'rebellion', 'social alienation', 'angst'],
      },
      connections: {
        related: [
          'alternative',
          'graffiti_pop',
          'metalhead',
          'punk',
          'indie',
          'sepia_blur',
          'indie_sleaze',
          'heroin_chic',
        ],
        subgenres: ['corporate_grunge', 'kinderwhore', 'soft_grunge', 'pastel_grunge'],
      },
      mediaCulture: {
        media: ['Singles (1992 film)', 'Hype! (1996 documentary)'],
        brands: ['Doc Martens', 'Converse'],
        figures: ['Kurt Cobain', 'Eddie Vedder', 'Chris Cornell', 'Layne Staley', 'Courtney Love'],
      },
      timeline: {
        preceded: ['glam_metal', 'punk'],
        succeeded: ['post-grunge', 'nu-metal', 'nu-grunge'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Post-Grunge_Maximalism',
    name: 'Post-Grunge Maximalism',
    id: 'post-grunge_maximalism',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/8/85/Original_adbc5899d8306cef2a86bdb4f2037a85.webp',
    description:
      'Post-Grunge Maximalism is a fashion aesthetic that was highly prevalent in the mid-to-late 2000s, characterized by its maximalist approach to design. The style is a fusion of post-grunge, hard rock, nu-metal, and tattoo culture, resulting in a distinctively embellished and often hyper-masculine look. The term was coined by researcher Evan Collins to retroactively name this previously unnamed but culturally significant trend.[1] The aesthetic is characterized by its use of intricate, overlapping graphics, heavy distressing, and luxury branding. It was popularized by brands like Affliction, Ed Hardy, and True Religion, and became strongly associated with the MMA, rock music, and nightclub scenes of the era. Post-Grunge Maximalism rose to prominence in the mid-2000s, a period that saw a departure from the minimalist and understated style of 1990s grunge. Brands like Affliction built their identity by aligning with the growing popularity of Mixed Martial Arts (MMA), with their graphic t-shirts becoming a uniform for fighters and fans alike.[2] Simultaneously, designer Christian Audigier brought the tattoo art of Don Ed Hardy into the mainstream with the Ed Hardy brand, plastering colorful, tattoo-inspired graphics onto t-shirts, hoodies, and trucker hats.',
    categories: ['fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: [
          'Rock Revival Style',
          'Butt-Rock Maximalism',
          'Affliction-core',
          'Ed Hardy-core',
          'Rawk Maximalism',
          'Rock Maximalism',
        ],
        decade: ['21th_century', '2000s'],
      },
      visualThemes: {
        motifs: [
          'Skulls',
          'crosses',
          'wings',
          'eagles',
          'gothic script',
          'tribal patterns',
          'heavy distressing',
          'foil prints',
          'rhinestones',
        ],
        colours: ['Muted colors (grey', 'brown', 'black)', 'often with bright', 'colorful graphics'],
        values: ['Hyper-masculinity', 'rebellion', 'rock music culture', 'luxury branding'],
      },
      connections: {
        related: [
          'bro_hoe',
          'cyber_grunge',
          'cybersigilism',
          'guido',
          'haunted_mound',
          'mc',
          'bling',
          'nu-metal',
          'olderbrothercore',
          'opium',
          'ur',
          'bling',
          'y2k_futurism',
        ],
      },
      mediaCulture: {
        brands: ['Affliction', 'Ed Hardy', 'True Religion', 'Christian Audigier'],
      },
      timeline: {
        preceded: ['grunge', 'nu-metal'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Soft_Grunge',
    name: 'Soft Grunge',
    id: 'soft_grunge',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/8/89/Groundgirl2.jpg',
    description:
      'Soft Grunge or Pale Grunge is an aesthetic based on simple photos with a color palette primarily consisting of white, grey, black, green, and blue. The aesthetic is believed to have appeared on Tumblr between 2013 and 2015 and lasted until approximately 2018.   Some photos are intended to be sad looking, often of someone suffering for love. Despite calling themselves grunge, followers of the aesthetic were fairly popular in the mainstream and connected to the rise of the Alternative, emo, pop, and indie music and fashion trends of the time, such as galaxy prints, black and white grids, and fandom merchandise. Because of their close-knit community on Tumblr, they developed a "not-like-other-girls" attitude, especially in contrast with the more mainstream and cheerful bright colors of the time. This style later declined, yet has gained short-term popularity in 2020 due to a desire to escape to the past.[1] Youth subcultures from the 1990s, including Grunge and Skateboarding culture, are some of the primary influences on this aesthetic.',
    categories: ['internet_aesthetics', 'music', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Pale Grunge'],
        decade: ['21th_century', '2010s'],
      },
      visualThemes: {
        colours: ['Black', 'white', 'grey', 'blue', 'green'],
      },
      connections: {
        related: [
          'brat_summer',
          'e-boy',
          'e-girl',
          'grunge',
          'traumacore',
          'sadgirl',
          'pastel_grunge2014_tumblr',
          'vaporwave',
          'weeaboo',
          'minimalism',
          'indie_sleaze',
          'health_goth',
          'skater',
        ],
      },
      mediaCulture: {
        brands: ['Voss', 'Fiji', 'Evian', 'American Apparel', 'Zara'],
      },
      timeline: {},
    },
  },
];
