import type { AestheticProps } from '@shared/types';

export const tumblr: AestheticProps[] = [
  {
    url: 'https://aesthetics.fandom.com/wiki/2014_Tumblr',
    name: '2014 Tumblr',
    id: '2014_tumblr',
    imageUrl: '',
    description: '',
    isVisible: true,
    categories: [],
    metadata: {},
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/2010s_Bright_Kawaii',
    name: '2010s Bright Kawaii',
    id: '2010s_bright_kawaii',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/4/44/2010s_brigh_kawaii_14.jpg',
    description:
      'Wiki-given name for Kawaii trends common on Tumblr and Instagram blogs in the mid-2010s. As a counterpart to 2010s Soft Kawaii, this page describes the aesthetic \n      that utilizes bright colors, video game and anime motifs, anime-inspired fashion, and pixel art. These are a Western perspective on the concurrent Japanese Yume Kawaii aesthetic, \n      which does not generally include references to anime and gamer culture, which Western Weeaboos incorporated, as well as the creation of Harajuku-inspired clothing with \n      Western brands and DIY styling.',
    categories: [],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['21th_century', '2010s'],
        creator: ['Western interpretation of Kawaii and Harajuku trends'],
      },
      visualThemes: {
        motifs: ['anime', 'arcades', 'mascots', 'school uniforms'],
        colours: ['bright pastels'],
      },
      connections: {
        related: ['2010s_soft_kawaii, 2010s_meme_maximalism', 'pastel_goth', 'weeaboo'],
        overlaped: ['yume_kawaii'],
      },
      mediaCulture: {
        platform: ['Tumblr'],
        brands: ['Pusheen the Cat', 'Sailor Moon'],
      },
      timeline: {
        succeeded: ['e-girl', 'kawaii_gamer'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/2010s_Soft_Kawaii',
    name: '2010s Soft Kawaii',
    id: '2010s_soft_kawaii',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/4/4a/2010s_soft_kawaii_1.jpg',
    description:
      '2010s Soft Kawaii is an offshoot of the Kawaii aesthetic based on trends in the 2010s, especially on the website Tumblr. It is largely based on Japanese mascot culture, \n      with the fashion elements being based on Himekaji and Girly Kei fashion trends of the time, as well as Korean fashion. There is also much overlap with 2014 Girly Tumblr. \n      Because this era coincides with the rise of Instagram, it was common for these photos to have a slightly sepia-toned filter and warmer lighting. \n      The colors most featured in this aesthetic are pink, gray, browns, creams, and mint green. Patterns are also commonly applied to multiple visuals, from phone cases to fashion. \n      English florals and Swiss dots are the most common, lending a more vintage look to the aesthetic. During this time, the mascots Pusheen the Cat, Rilakkuma, \n      and Domo-kun were especially popular and appeared as plushies, phone cases, and digital stickers.',
    categories: ['internet_aesthetics', 'fashion_styles'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['21th_century', '2010s'],
        location: ['Japan and the West'],
      },
      visualThemes: {
        motifs: ['kawaii mascots', 'sweets', 'florals'],
        colours: ['pink', 'cream', 'mint green', 'brown'],
      },
      connections: {
        related: ['kawaii', 'twee'],
        overlaped: ['2014_girly', 'girly_kei', 'himekaji', 'positivity_kawaii', 'sweet_lolita'],
      },
      mediaCulture: {
        platform: ['Tumblr and Instagram'],
        brands: ['Pusheen the Cat', 'Rilakkuma', 'Domo'],
      },
      timeline: {
        preceded: ['heisei_retro'],
        succeeded: ['choco_girl', 'shoujo'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/2014_Girly',
    name: '2014 Girly',
    id: '2014_girly',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/3/36/Rosytumblrbloggirly.jpg',
    description:
      'The aesthetic resurfaced on social media app TikTok between late 2022 and reached its peak in summer 2024, following the "2024 is the new 2014" trend, due to users \n      longing for the energy it gave. The visuals in this aesthetic are girly: They include Victoria\'s Secret backstage photos, Starbucks drinks, cakes, and comfy rooms with floral \n      bedsheets. The photos are usually edited with the "Amaro" filter on Instagram.',
    categories: ['internet_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Tumblr It Girl', 'Rosyblog', 'girly'],
        decade: ['21th_century', '2010s'],
        creator: ['Ariana Grande', 'Dove Cameron', 'Candice Swanepoel', 'ralu cakes', ''],
      },
      visualThemes: {
        colours: ['pink', 'cream white', 'beige', 'mint'],
        values: ['kindess', 'femininity', 'being grateful'],
      },
      connections: {
        related: ['2014_tumblr', 'barbiecore', 'pale_grunge', 'pink_princess', 'quality_tumblr', 'shabby_chic'],
        overlaped: ['2010s_soft_kawaii'],
      },
      mediaCulture: {
        media: ['Tumblr', 'Tik', 'Tok'],
        brands: [
          'Victoria Secrets',
          'UGG',
          'PINK',
          'Essence',
          'ted baker',
          'cath kidston',
          'Versace',
          'Dolce & Gabbana',
          'Dior',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Delicate_Sweet',
    name: 'Delicate Sweet',
    id: 'delicate_sweet',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/08/Middlepotcollage.png',
    description:
      'The aesthetic originated on tumblr from the mid 2010s, and largely takes inspiration from Cult Party Kei, which was a Japanese style that rose in popularity at that time. It co-existed and shared many visuals with the Morute community, except this one is entirely uninvolved in morbid themes. Rather, this aesthetic focuses on feelings of comfort, cuteness, and safety. The term for this aesthetic was coined for this wiki and only for documentation purposes. Originally, the aesthetic went without a name on Tumblr and could be found on individual blogs through tags such as #pink, #cute, #delicate (hence the name), etc. However, now it can be associated with the Coquette community. This aesthetic appeared in the mid-2010s on Tumblr. Photographers such as @jess_woods and @underwata and compilers such as @andante-grazioso (both are now deleted) posted images fitting this aesthetic.',
    categories: ['fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Pinkcore', 'Softette'],
        decade: ['21th_century', '2010s'],
      },
      visualThemes: {
        motifs: [
          'Lace',
          'doilies',
          'fabric textures',
          'stuffed animals',
          'pillows',
          'vintage nightgowns',
          'baked goods',
          'embroidery/sewing',
          'angels',
          'dolls',
        ],
        colours: ['Washed out baby pink', 'baby blue', 'white', 'brown', 'beige'],
        values: ['Kindness', 'comfort', 'sleepiness', 'purity', 'innocence', 'softness', 'self care'],
      },
      connections: {
        related: [
          'angelcore',
          'cult_party_kei',
          'dreamy_indie_girlhood',
          'yume_kawaii',
          'babycore',
          'grandparentcore',
          'larme_kei',
          'rococo',
          'soft_boy',
          'soft_girl',
          'classic_lolita',
          'mori_kei',
          'ethereal',
          'romantic_academia',
          'vanilla_girl',
          'morute',
          'coquette',
          'gloomy_coquette',
        ],
      },
      mediaCulture: {
        platform: ['Tumblr'],
        media: ['poofties'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Hipster',
    name: 'Hipster',
    id: 'hipster',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/4/40/Hipster_moodb.png',
    description:
      'Hipster is a broad subculture that is stereotypically composed of young adults who reside primarily in gentrified neighborhoods. It is broadly associated with indie and alternative music and genres, such as jazz, folk, indie rock, and electronic rock. Hipsters also frequently flaunt a varied non-mainstream fashion sensibility, wearing vintage and thrifted clothing; hold pacifist and green views; are often vegan; consume organic and artisanal foods, and craft alcoholic beverages; and live alternative lifestyles. The roots of the hipster aesthetic date back to the 1940s, but the modern-day version did not reach the height of its popularity until the late 2000s to early 2010s.[1] Hipster is also a perjorative that refers to people within alternative subcultures that are considered "cutting edge" in that they deviate from the mainstream purposefully. However, rather than alternative subcultures which are visually and philosophically a rejection of majority trends (such as Punk), Hipsters seek to be more familiar with the mainstream and deviate it out of a search for uniqueness while still participating within the mainstream. Because of this, what was deemed Hipster could be quite broad, as any aesthetic linkage with the past, interest in art and music, or "quirky" hobbies such as DIY made one a "hipster."[2] As a note, the word hipster coincided/created the beginnings of aesthetic culture on social media, making this mindset highly influential in internet culture. The term "hipster" originated in the late 1930s and was popularized in the early \'40s to describe jazz fans, a variation on the earlier "hepster" or "hep cat." Cab Calloway\'s A Hepster\'s Dictionary was published in 1938 as a guide to jazz slang. A mention of the musical superstar\'s book in the New York Amsterdam News, in which it was misprinted as A Hipster\'s Dictionary, may have popularized the spelling with an I.[3]',
    categories: ['character_tropes', 'lifestyle', 'subcultures', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['20th_century', '21th_century', '1940s', '1990s', '2000s'],
      },
      visualThemes: {
        motifs: ['Vintage', 'bikes', 'music'],
        colours: [
          'Any colors; either dissonant',
          'intentionally unstylish colors',
          'nature-based earth tones',
          'or gothic/artist black',
        ],
        values: [
          'Independence',
          'creativity',
          'artistry',
          'education',
          'rejection of corporate or mainstream products and attitudes',
          'veganism',
          'sustainability',
          'alternative music',
          'vintage style',
        ],
      },
      connections: {
        related: [
          'beatnik',
          'bloghouse',
          'dandy',
          'indie',
          'galaxy_print',
          'hipness_purgatory2014_tumblr',
          'recession_pop',
          'emo',
          'grunge',
          'hippie',
          'indie_sleaze',
          'lumberjack',
          'minimalism',
          'nerd',
          'normcore',
          'nu-goth',
          'folk_punk',
          'party_rock',
          'scene',
          'stilyagi',
          'yabi',
        ],
        overlaped: ['indie_sleaze', 'indie', 'hipness_purgatory'],
      },
      mediaCulture: {
        brands: ['Pabst Blue Ribbon', 'American Apparel', 'Whole Foods', 'Sub Pop'],
      },
      timeline: {
        preceded: ['beatnik', 'hippie', 'mission_school'],
        succeeded: ['downtown_girl', 'whimsy_twee'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Indie_Sleaze',
    name: 'Indie Sleaze',
    id: 'indie_sleaze',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/b/b0/Indie_sleaze_moodb.png',
    description:
      'Indie Sleaze is an aesthetic that describes the hedonistic, global party scene that flourished from roughly 2005 to 2014. It represented a more "authentic" and debaucherous reaction to the polished McBling culture of the early-mid 2000s, reflecting the economic uncertainty and creative energy of the late-aughts. The era\'s visual identity is inextricably linked to the raw, voyeuristic, and high-flash photography of documentarians like The Cobrasnake, which captured the messy, maximalist fashion of the time. The look was an eclectic mix of high and low: American Apparel basics were paired with ripped tights, vintage band t-shirts, skinny jeans, and neon accents. Musically, the aesthetic is synonymous with the Bloghouse phenomenon, where indie rock, electro, and dance-punk acts like LCD Soundsystem, M.I.A., and Crystal Castles gained popularity through music blogs and MySpace. During its time, Indie Sleaze also overlapped with the Hipster scene, coming from the taste in music, fashion, and lifestyle that differed from mainstream available multinational brands and pop music and required "being in the know" to understand. The term "Indie Über-Sleaze" was coined in 2018 by Dalia Barillaro of CARI, later shortened to "Indie Sleaze." In 2021, the term went viral on TikTok, leading to renewed interest in the aesthetic. Indie Sleaze captures a specific "grimy-glam" moment, that existed between the decline of mainstream McBling and the rise of polished Instagram influencer culture.',
    categories: ['consumer_aesthetics', 'internet_aesthetics', 'music', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Indie Über-Sleaze (original term)', 'Hipster (colloquial)', 'Post-Underground'],
        decade: ['21th_century', '2000s'],
        location: ['New York (Lower East Side)', 'London (Shoreditch)', 'Los Angeles (Silver Lake)'],
      },
      visualThemes: {
        motifs: [
          'Amateur flash photography',
          'smudged eyeliner',
          'messy hair',
          'ripped tights',
          'deep V-necks',
          'neon accents',
          'band t-shirts',
          'skinny jeans',
          'metallic fabrics',
          'American Apparel basics',
          'cigarettes',
        ],
        colours: ['Black', 'white', 'neon pink', 'neon green', 'metallic silver'],
        values: [
          'Hedonism',
          'irony',
          'performed authenticity',
          'nightlife documentation',
          'chaotic energy',
          'rejection of polish',
          'provocativeness',
          'sexuality',
        ],
      },
      connections: {
        related: [
          'bloghouse',
          'brat_summer_revivalelectroclash',
          'geek_chic',
          'hedi_boy',
          'heroin_chic',
          'hipster',
          'indie',
          'kinderwhore',
          'mc',
          'bling',
          'new_rave',
          'recession_pop',
          'swag',
          'twee',
          'urbancore',
        ],
      },
      mediaCulture: {
        platform: ['The Cobrasnake', 'My', 'Space', 'Music Blogs', 'Facebook (Early albums)'],
        brands: ['American Apparel', 'Urban Outfitters', 'Cheap Monday', 'Ray-Ban (Wayfarers)'],
        figures: [
          'The Cobrasnake (Mark Hunter)',
          'Cory Kennedy',
          'Sky Ferreira',
          'Uffie',
          'M.I.A.',
          'Crystal Castles',
          'Agyness Deyn',
          'LCD Soundsystem',
          'Jeremy Scott',
        ],
      },
      timeline: {
        preceded: ['mcbling', 'electroclash'],
        succeeded: ['soft_grunge2014 tumblr'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Morute',
    name: 'Morute',
    id: 'morute',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/1/19/Morute_mb.png',
    description:
      'Morute, a name combining the words "morbid" and "cute," is an aesthetic created in the early 2010s that expresses the dichotomy between the hyper-femininity and softness of a childhood/girlhood in the past with the darker imagery of true crime and Regional Gothic elements. In the community, users often use it as an outlet for expressing trauma, especially those surrounding eating disorders and child abuse. The community largely developed from the music of Nicole Dollanganger and influential photographers such as Jess Woods and milliedollgraves, who have since deactivated. Many visuals suggest physical abuse, sexual assault/molestation, emotional abuse, self-destruction, religious trauma, and physical disability. The child-like imagery serves as a desire to return to a girlhood that was ripped away from them, with the Christian, angelic, and cute motifs being an idealization of purity and innocence. Religious guilt is a common motif, with the desire to go to Heaven, but feeling unable due to the victim being "dirtied" with whatever traumatized them. This can create some overlap with Catholic Horror. The idea of ‘dirtiness’ and rot is a common theme. Poverty within small-town Americana is also present, and it reflects the influence of horror movies and the idea of home being sullied and unsafe. It is a precursor to Traumacore, and that aesthetic is an example of convergent evolution, wherein two aesthetics express the same thing, but the later community is relatively unaware of its predecessor and its influences. The aesthetic is one that has largely fallen out of popularity due to the current notoriety of Traumacore, the insular community, mental recovery of many influencers, and discourse surrounding the aestheticization of dark themes. The community itself does not emphasize the necessity of actually having trauma. Many simply are visually attracted to the contrast between cutesy, girly, childish aesthetics with dark, creepy, Gothic aesthetics, and there is no need to discuss or vent about past experiences.',
    categories: ['internet_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Creepy Cute Tumblr', 'Morbid Cute', 'Morbid Dolly', 'Morbidette', 'Sad Babydoll', 'Sad Bbydoll'],
        decade: ['21th_century', '2010s'],
        creator: ['Nicole Dollanganger'],
      },
      visualThemes: {
        motifs: ['Death', 'cuteness', 'trauma', 'horror', 'girlhood', 'religion', 'depression'],
        colours: ['Pink', 'white', 'black', 'and gray'],
        values: [
          'Depression',
          'nihilism',
          'vulnerability',
          'religious guilt',
          'interest in the macabre',
          'feeling dirty after abuse',
          'desire to be innocent',
          'nostalgia',
        ],
      },
      connections: {
        related: [
          'catholic_horror',
          'cult_party_kei',
          'cutegore',
          'delicate_sweet',
          'gloomy_coquette',
          'gothic',
          'kinderwhore',
          'midwest_gothic',
          'mochette',
          'nymphet',
          'preachers_daughter',
          'slavic_violence_tumblr',
          'southern_gothic',
          'teethcore',
          'traumacore',
          'trailer_park_princess',
          'waif',
          'yami_kawaii',
        ],
      },
      mediaCulture: {
        media: [
          'Flowers in the Attic (film and book series)',
          'Other books/films by VC Andrews',
          "Mark Ryden's art",
          'Nicole Dollanganger',
          "Risa Mehmet's art",
          'Welcome to the Dollhouse (1995)',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Pink_Parisian',
    name: 'Pink Parisian',
    id: 'pink_parisian',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/4/49/Pink_parisian_moodboard.png',
    description:
      'As the aesthetic was developed by fashion brands from the 1930s-1960s, most of the pieces included take direct inspiration from Chanel, Dior, and Louis Vuitton. Followers of Vintage Parisian also seek to emulate movie stars such as Audrey Hepburn and Marilyn Monroe, as well as some modern hyper-feminine characters and celebrities such as Blair Waldorf and Ariana Grande. In line with the lifestyle that emphasizes relaxation and romance, there is a strong emphasis on wearing lingerie and loungewear. The colors involved are black and white, red, pastels, and precious metals. Multiple textures include: satin, velvet, lace, wool, tweed, marabou feathers, fur, and high-end linen. Fashion pieces include: Perfume is a large component of this aesthetic; not only the fragrance itself, but also the perfume bottles which are oftentimes displayed as decor or photographed as part of a vanity display with other cosmetic items (makeup, skin care, etc.). The fragrances popular with this aesthetic mainly come from French perfume houses (Chanel, Dior, Guerlain, Yves Saint Laurent, etc.) and have simple and elegant packaging. High-end designer brand perfume is expensive and therefore seen as luxurious, adding to its appeal in this aesthetic.',
    categories: ['architectural_styles', 'internet_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Vintage Parisian'],
        decade: ['20th_century', '1930s', '1940s', '1950s', '1960s'],
      },
      visualThemes: {
        motifs: [
          'Luxury goods',
          'perfume',
          'make-up',
          'roses',
          'vintage movies',
          'jazz music',
          'love',
          'French cuisine',
        ],
        colours: ['Black', 'white', 'gold', 'and pink'],
        values: ['Romanticism', 'self-care', 'beauty', 'elegance'],
      },
      connections: {
        related: [
          'angelcore',
          'bon_chic_bon_genre',
          'coquette',
          'boujee',
          'chic_modernist',
          'french_girly',
          'haussmann_paris',
          'old_hollywood',
          'pink_princess',
          'romanticism',
          'romantic_academia',
          'parisian_girly',
        ],
      },
      mediaCulture: {
        media: ['Sabrina (1954)'],
        brands: ['Chanel', 'Dior', 'Tiffany & co.', 'Louis Vuitton', 'Laduree'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Quality_Tumblr',
    name: 'Quality Tumblr',
    id: 'quality_tumblr',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/0c/Quality_tumblr_moodb.png',
    description:
      "Quality Tumblr is an aesthetic originating from the eponymous website circa 2012. It shares elements with Basic Girl and 2014 Girly  and has an audience primarily consisting of teenage girls. Quality Tumblr's specific visuals are brightly colored images of certain products and branding that were popular amongst the demographic. Additionally, other trends of that era, such as certain films and novels, quotes, and different fashions are included.",
    categories: ['internet_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['21th_century', '2010s'],
      },
      visualThemes: {
        colours: ['Neon pastels', 'black', 'and pink'],
      },
      connections: {
        related: ['basic_girl', 'normcore', 'pale_grunge2014_girly'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Sadboi',
    name: 'Sadboi',
    id: 'sadboi',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/6/65/Yunglean2.png',
    description:
      'DrainE-BoyEmo RapLo-fi ArtSadgirl (counterpart)SimpsonwaveSoft BoyTrap MetalTrxshVaporwave Sadboi (also written as Sad Boy) is an internet aesthetic and masculine archetype that emerged on Tumblr and SoundCloud in the early 2010s. The terminology originates from the "Sad Boys" music collective, founded by Swedish rapper Yung Lean and producers Yung Gud and Yung Sherman in 2012.[1] The aesthetic visually materializes themes of loneliness and anxiety through a synthesis of streetwear, early 2000s raster graphics, and Cloud Rap iconography. Unlike the parallel Sadgirl aesthetic, which draws from a long tradition of feminine literary melancholy and Soft Grunge, Sadboi relies on a sense of irony, commercial brand appropriation (e.g., Arizona Iced Tea), and lo-fi imagery.',
    categories: ['internet_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Sad Boy'],
        decade: ['21th_century', '2010s'],
      },
      visualThemes: {
        motifs: [
          'Lo-fi and distorted digital effects (VHS',
          'glitching',
          'pixelation)',
          'anime/cartoon edits (e.g.',
          'Bart Simpson)',
          'roses (often withered)',
          'bucket hats',
          'sportswear (Nike',
          'Adidas)',
          'Arizona Iced Tea',
          'Fiji Water',
          'Japanese lettering',
          'digital manipulation of sadness',
          'cloud imagery',
        ],
        colours: [
          'Desaturated blues and purples',
          'dark greys/black',
          'often contrasted with neon/pastel digital effects',
        ],
        values: [
          'Emotional vulnerability',
          'irony',
          'nostalgia',
          'self-expression through hip-hop/trap',
          'reclaiming sensitivity',
        ],
      },
      connections: {
        related: [
          'dead_inside',
          'drain',
          'e-boy',
          'emo_rap',
          'lo-fi_art',
          'sadgirl_counterpartsimpsonwave',
          'soft_boy',
          'trap_metal',
          'trxsh',
          'vaporwave',
        ],
      },
      mediaCulture: {
        platform: ['Tumblr', 'You', 'Tube', 'Sound', 'Cloud'],
        media: ['The Simpsons (Bart edits)', '90s/2000s video game aesthetics'],
        brands: ['Arizona Iced Tea', 'Fiji Water', 'Nike', 'Adidas'],
        figures: ['Yung Lean', 'Lil Peep', 'XXXTentacion', 'Joji'],
      },
      timeline: {
        preceded: ['hipster'],
        succeeded: ['e-boy'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Sadgirl',
    name: 'Sadgirl',
    id: 'sadgirl',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/07/Eca34de022b0709f206f0680160e1919.jpg',
    description:
      "Sadgirl (also written as Sad Girl) is an internet aesthetic and feminine archetype that emerged on Tumblr in the early 2010s, defined by the expression and romanticization of melancholy, anxiety, and loneliness through specific visual and literary elements.[1] The style turns personal pain into a shared aesthetic, representing an ambivalent relationship with mental health and traditional expectations of feminine happiness. The aesthetic's lineage draws from centuries of art and literature that idealize the tragic female figure, from Shakespeare's Ophelia to the doomed protagonists of The Virgin Suicides.[2] The lineage of this archetype traces back to figures in classic literature and art who portray despair as an idealized and beautiful state. Shakespeare's tragic heroines, Ophelia and Juliet, serve as early examples whose fates are intertwined with elegant despair. This connection was visually reinforced by John Everett Millais' 1851 painting, Ophelia, which depicted the character as beautiful and composed even in death, emphasizing the correlation between beauty and destruction.[2]",
    categories: ['internet_aesthetics', 'microtrends', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Sad Girl'],
        decade: ['21th_century', '2010s'],
      },
      visualThemes: {
        motifs: [
          'Runny mascara',
          'rainy weather',
          'black tights',
          'cigarettes',
          'introspective quotes (Plath',
          'Poe)',
          'tragic female figures (Ophelia',
          'Juliet)',
          'VHS filters',
          'sad faces',
          'self-deprecating text',
        ],
        colours: [
          'Predominantly desaturated and monochromatic (black',
          'gray',
          'dull blue)',
          'with occasional stark contrast (dull reds',
          'black eyeliner)',
        ],
        values: [
          'Self-expression',
          'emotional vulnerability',
          'romanticization of sadness',
          'finding beauty in pain',
          'validation',
          'anti-perfectionism',
        ],
      },
      connections: {
        related: ['e-girl', 'emo_rap', 'euphoric', 'pastel_grunge', 'sadboi_counterpartsoft_grunge', 'waif'],
        overlaped: ['soft_grunge', 'emo_rap'],
      },
      mediaCulture: {
        platform: ['Tumblr', 'Instagram', 'Tik', 'Tok (revival)'],
        media: [
          'The Virgin Suicides (1999)',
          'Marie Antoinette (2006)',
          'Skins (Effy Stonem)',
          'The Bell Jar (Sylvia Plath)',
          'Euphoria (Rue Bennett)',
          "Lana Del Rey's Tropico (2013)",
          'American Horror Story: Murder House (Violet Harmon)',
        ],
        figures: ['Lana Del Rey', 'Sylvia Plath', 'Effy Stonem', 'Violet Harmon'],
      },
      timeline: {
        preceded: ['emo', 'grunge'],
        succeeded: ['e-girl'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Swag',
    name: 'Swag',
    id: 'swag',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/c/c6/Swag_moodb.png',
    description:
      'The Swag era began in the latter half of the 2000s, emerging as a distinct movement within hip-hop culture. Its initial catalyst was the "jerkin\'" or "jerk" dance movement, which originated in Los Angeles and was popularized by the hip-hop duo New Boy\'z with their 2009 viral hit, "You\'re a Jerk." This song and its accompanying dance created a cultural phenomenon, establishing the core fashion of the emerging Swag aesthetic: bright colors, skinny jeans, and a DIY, individualistic approach to style.[1] The aesthetic quickly moved beyond the Jerk scene and was adopted by a wider range of hip-hop artists like Soulja Boy, Tyga, and Wiz Khalifa, who helped popularize the term "swag" itself. The subculture flourished in the early 2010s, a period defined by the rise of social media platforms like Tumblr, which became a primary hub for sharing fashion and music related to the aesthetic. By the mid-2010s, the style began to fade as hip-hop fashion shifted towards the darker, more minimalist look of the "Hypebeast" era. The fashion of the Swag era was a vibrant and eclectic mix of streetwear, skate culture, and hip-hop influences. The look was defined by a specific silhouette, typically combining tight-fitting pants with looser tops. Key garments included brightly colored skinny jeans, graphic t-shirts, and hoodies.',
    categories: ['lifestyle', 'music', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Jerk', 'Swag Era'],
        decade: ['21th_century', '2000s', '2010s'],
        location: ['United States (primarily California)'],
      },
      visualThemes: {
        motifs: ['Snapback hats', 'graphic tees', 'skinny jeans', 'high-top sneakers', 'gold chains', '"jerk" dance'],
        colours: ['Bright', 'high-contrast colors: red', 'black', 'purple', 'neon green'],
        values: ['Confidence', 'individuality', 'street fashion', 'party culture', 'online presence'],
      },
      connections: {
        related: [
          '2014_tumblr',
          'baddie',
          'bloghouse',
          'hip-hop',
          'hypebeast',
          'jejemon',
          'party_rock',
          'scene',
          'urbancore',
        ],
        overlaped: ['bloghouse', 'recession_pop', 'indie_sleaze', 'hipster', 'bro_hoe2014_tumblr'],
      },
      mediaCulture: {
        brands: ['Obey', 'Diamond Supply Co.', 'Crooks & Castles', 'Trukfit', 'Beats by Dre'],
        figures: ["New Boy'z", 'Soulja Boy', 'Tyga', 'Chris Brown', 'Odd Future'],
      },
      timeline: {
        preceded: ['mcbling', 'hip-hop', 'bro_hoe'],
        succeeded: ['hypebeast'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Twee',
    name: 'Twee',
    id: 'twee',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/5/5a/Twee_moodb.png',
    description:
      "The aesthetic gained prominence in the late 1980s with the emergence of this distinct musical style and its associated cultural expressions. It encompasses various forms, including fashion, film, music, and even food trends. In 2014, Marc Spitz's book, Twee: the gentle revolution in music, books, television, fashion, and film, codified the aesthetic, labeling it as \"the most powerful youth movement since Punk and Hip-Hop.\" Adherents of the Twee aesthetic are sometimes associated with the broader Hipster aesthetic, though Hipster encompasses a wider array of alternative styles. As described by James Parker of The Atlantic, \"Twee's core values include 'a healthy suspicion of adulthood'; 'a steadfast focus on our essential goodness'; 'the cultivation of a passion project' (T-shirt company, organic food truck); and 'the utter dispensing with of 'cool' as it's conventionally known, often in favor of a kind of fetishization of the nerd, the geek, the dork, the virgin.'\" Visually, the aesthetic involves the re-contextualization of outdated habits and objects, which gain novelty through their uniqueness in comparison to mainstream trends. Idiosyncrasy and an eclectic blend of colors and vintage items are prominent indicators of the Twee visual style.",
    categories: ['music_genres', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Twee Pop'],
        decade: ['20th_century', '1980s'],
        location: ['United Kingdom (especially England)', 'United States'],
        creator: ['C86 (compilation)', 'Sarah Records', 'K Records'],
      },
      visualThemes: {
        motifs: [
          'Childlike innocence',
          'vintage objects',
          'delicate imagery',
          'idiosyncratic elements',
          'eclectic color blends',
          'hearts',
          'Manic Pixie Dream Girl archetype',
        ],
        colours: ['Pastel hues', 'bright primary and secondary colors (often in eclectic combinations)'],
        values: [
          'Nerdiness',
          'sweetness',
          'romanticism',
          'shyness',
          'carefree attitude',
          'simplicity',
          'suspicion of adulthood',
          'essential goodness',
          'cultivation of passion projects',
          'rejection of conventional "cool"',
          'romanticization of the nerd/geek/dork/virgin archetypes',
        ],
      },
      connections: {
        related: [
          'art_hoe',
          'cybertwee',
          'dolly_girl',
          'dreamy_indie_girlhood',
          'geek_chic',
          'hipness_purgatory',
          'poppare',
          'hipster',
          'indie',
          'shibuya-kei',
          'whimsy_twee',
        ],
        overlaped: ['indie'],
      },
      mediaCulture: {
        media: [
          'Twee: The Gentle Revolution in Music',
          'Books',
          'Television',
          'Fashion',
          'and Film (2014) by Marc Spitz',
        ],
        brands: ['Modcloth', 'Princess Highway'],
      },
      timeline: {
        preceded: ['post-punk'],
      },
    },
  },
];
