import type { AestheticProps } from '@shared/types';

export const y2k: AestheticProps[] = [
  {
    url: 'https://aesthetics.fandom.com/wiki/90s_Cool',
    name: '90s Cool',
    id: '90s_cool',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/f/ff/Untitled_design_%2829%29.png',
    description:
      "90s Cool became more prominent after the success of The Matrix movies. During The Matrix hype around 1999/2000, studios were quick to release the next \n      Matrix by taking influence from the film's various styles. The aesthetic was mostly known for its use of Bullet Time (a slow motion camera tracking shot), \n      costumes in Y2K style (black leather trenchcoats, combat boots, Oakley glasses, bullet proof vests, latex catsuits, tactical gear, and dark formal wear or garb \n      inspired by American, Japanese, Hong Kong, and Chinese action films), and plot settings in post-Cold War Eastern Europe (typically with underworld themes) due to the collapse \n      of the Iron Curtain (e.g. Goldeneye, Mission: Impossible). ",
    categories: [],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['The Matrix Effect', 'Bullet Time'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'Bullet time action',
          'martial arts movies',
          'slo-motion sequences',
          'CGI',
          'Y2K style costumes',
          'action',
          'cyberpunk settings',
          'digital rain',
          'Hollywood-style hacking/computer cracking',
        ],
        colours: ['green', 'blue', 'yellow', 'black'],
        values: ['Lone savior complex', 'a massive emphasis on "cool"', 'Post-Matrix action film-making'],
      },
      connections: {
        related: [
          'y2k_futurism',
          'techwear',
          'metalheart',
          'nu-metal',
          'cyberdelic',
          'cybergen-x_corporate',
          'related_aestheticsolderbrothercore',
          'abstract_tech',
          'alternative',
          'berlin_techno_fashion',
          'biopunk',
          'corporate_grunge',
          'cyberprep',
          'cyberpunk',
          'early_cyber',
          'gen_x_soft_club',
          'grunge',
          'hacker_chic',
          'goth',
          'mallgoth',
          'industrial',
          'metalheart',
          'nu-metal',
          'cyberdelia',
          'raver',
          'y2kchromecore',
          'techwear',
          'teenpunk',
          'y2k_futurism',
          'poster_gal',
        ],
      },
      mediaCulture: {
        media: ['The Crow', 'The Matrix', 'Blade', 'Max Payne', 'Splinter Cell', 'GTA II & III', 'Metal Gear Solid'],
        figures: [
          'Wesley Snipes',
          'P.O.D',
          'Brad Pitt',
          'Limp Bizkit',
          'Rage Against The Machine',
          'Milla Jovovich',
          'Lara Croft',
          'Jet Li',
          'Vin Diesel.',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Chromecore',
    name: 'Chromecore',
    id: 'chromecore',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/f/f2/Fbf8a529da997f96cd19e68c1a7f5604.jpg',
    description:
      'Chromecore (also known as Y2K Chromecore) is a design aesthetic that was popular from roughly 1999 to 2006, a subgenre of Y2K Futurism. It focused on metallic-looking objects and products, most commonly CDs, DVDs, computers, video games, toys, phones, and digital cameras, having a sleek, chromatic gray texture. It was characterized by a distinct aesthetic period, encapsulating fashion, hardware design, and furnishings shining with technological optimism. It started as an branch of Y2K Futurism, becoming a common color scheme on product design and advertisement in the early-mid 2000s, that was unique yet clean for its time. Most examples described as "Chromecore" are machinery and handheld gaming devices of the Y2K era, also overlapping somewhat with Frutiger Aero. Its popularity declined in the late 2000s in favor of materials like anodized aluminum, glass, and carbon fiber, and a shift to more "nature-oriented" designs of Frutiger Aero. This decline happened due to oversaturation, short durability in some products, and lack of colorful and diverse design possibilities. The visuals consists of shiny graphics and textures that have a metal chrome, bead blast or stainless steel finish to it. Within product design, the visuals are achieved with the use of silver plastic, that mimics the chrome finish. The silver and gray tones seen in the aesthetic are bright, reflective, clean and lustrous. Molded curves and shapes are also key features of this aesthetic too.',
    categories: ['design_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Y2K Chromecore'],
        decade: ['20th_century', '21th_century', '1990s', '2000s'],
      },
      visualThemes: {
        motifs: ['Metallic and chrome textures', 'molded curves and shapes'],
        colours: ['Silver', 'gray', 'white', 'black', 'blue'],
      },
      connections: {
        related: ['cybersigilism', 'frutiger_aero', 'metalheart', 'mizuiro', 'retrofuturism', 'technozeny2k_futurism'],
      },
      mediaCulture: {
        media: ['Jetix'],
        brands: ['Sony', 'Motorola', 'Samsung', 'Nintendo', 'Nikon', 'Nokia', 'Sanyo', 'Do', 'Co', 'Mo', 'LG'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Cyber_Stylin%27',
    name: "Cyber Stylin'",
    id: 'cyber_stylin',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/8/86/747df633a6755dc86291c6173e8eb544.jpg',
    description:
      "Cyber Stylin' is inspired by dress up games from the mid-2000s to early 2010s, pixel dolls (also known as Dollz),[1] dolls from the 2000s/2010s, and fashionable illustrations of girls from the 2000s/2010s. The term Cyber Stylin' can be used to generalize the common art styles during the time period, as well as virtual/pixel games, drawings, and illustrations meant for young girls at the time. Despite the name Cyber Stylin' being a blanket term, there are many different art styles within it, usually depending on the artist.",
    categories: ['internet_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Dress Up Doll', 'Dress Up Girl', 'Dollz', 'Dollzcore', 'Chicaloca', 'Fashionista', 'Y2K Doll'],
        decade: ['21th_century', '2000s', '2010s'],
      },
      visualThemes: {
        motifs: ['Femininity', 'nostalgia', 'youth'],
        colours: ['Pink', 'purple', 'white', 'brown', 'blue', 'black'],
        values: ['Self-love', 'self care', 'personal expression', 'feminimity'],
      },
      connections: {
        related: [
          'barbiecore',
          'glitter_graphics',
          'tweencore',
          'mc',
          'bling',
          'bubblegum_bitch_gyaru',
          'vectordelia',
          'old_web',
          'curly_girly',
          'y2k_futurism',
        ],
      },
      mediaCulture: {
        media: [
          'girlsgogames.com',
          'My',
          'Scene',
          'Candybar Dollmaker',
          'Miss Bimbo',
          'Style Dollz',
          'Chicaloca',
          'Sugar Luxe',
        ],
        brands: [
          'Pink',
          'Bebe',
          'Uggs',
          "Claire's",
          'Justice',
          "Victoria's Secret",
          'Laneige',
          'Louis Vuitton',
          'Vivienne Westood',
          'Chanel',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Gen_X_Soft_Club',
    name: 'Gen X Soft Club',
    id: 'gen_x_soft_club',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/7/70/Gen-X-Soft-Club.jpg',
    description:
      'Gen X Soft Club was particularly popular in the United Kingdom at this time, succeeding the initial Britpop/Cool Britannia wave of the mid-1990s. Artists in the Electronica (Fatboy Slim, The Chemical Brothers, Stereolab, Massive Attack) and Post-Britpop (Radiohead, Travis, Starsailor, Doves) genres were seen as representing Y2K/GXSC in both sound and album covers. GXSC\'s popularity was a movement in futurist aesthetics that spawned from the economic recovery and growing technology industry of the mid-late 1990s. Some had criticisms about the overly optimistic, "bubblegum" styles of Y2K Futurism and McBling. A notable shift in the visual mood of these styles happened during the turn of the millennium, mainly among Gen Xers and older Millennials. Today, the aesthetic is making a comeback as styles like Y2K Futurism and Frutiger Aero return to the public eye in the 2020s. Artists like George Clanton, CFCF, and Doss overlap a lot with GXSC and push forward with the style to this day.',
    categories: ['consumer_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['GXSC'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'Y2K-era vector graphics',
          'Helvetica fonts',
          'metro/train stations',
          'airports',
          'urban architecture/cityscapes',
          'lomo lens effects',
          'color filters',
          'blurring',
          'bloom',
          'bokeh',
          'vignettes',
        ],
        colours: ['Natural and muted colors such as greens', 'blues', 'beiges', 'tans and greys/black'],
        values: ['A more natural', 'softer look into 90s/2000s futurism', 'with an urban twist.'],
      },
      connections: {
        related: [
          'britpop',
          'corporate_grunge',
          'flat_design',
          'frutiger_aero',
          'gen_z_soft_club_revivalglobal_village_coffeehouse',
          'grunge',
          'lo-fi',
          'metalheart',
          'milipili',
          'hexatron',
          'abstract_tech',
          'millennium_disco',
          'minimalism',
          'mission_school',
          'neubrutalism',
          'raver',
          'shibuya_punk',
          'supergraphic_ultramodern',
          'ultramodern_revival',
          'groovival',
          'rivethead',
          'technozen',
          'ur',
          'bling',
          'vectorhearty2k_futurism',
          'zen-x',
        ],
      },
      mediaCulture: {
        brands: ['Ninja Tune'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/FantasY2K',
    name: 'FantasY2K',
    id: 'fantasy2k',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/d/dd/Princess_unicorn.jpg',
    description:
      "The Mists of Avalon (2001)  Ella Enchanted (2004)  Robin Hood (2006-2009)  Merlin (2008-2012) Betsey Johnson   Jean Paul Gautier   Versace The aesthetic takes an unapologetically kitsch approach in its disregard for historical accuracy in favor of contemporary trends. For this reason, it is often adopted with self-aware irony, particularly in satirical media such as A Knight's Tale or Ella Enchanted.",
    categories: ['design_aesthetics', 'fashion_styles', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Medieval Y2K'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'crochet',
          'lace up details',
          'corsets/stays',
          'long skirts',
          'hip belts',
          'flare sleeves',
          'sheer fabric',
          'layering',
          'embellishments',
        ],
        colours: ['jewel tones', 'earth tones', 'green', 'brown', 'orange', 'red', 'yellow', 'blue', ''],
      },
      connections: {
        related: [
          'bohemian',
          'camp',
          'cottagecore',
          'ethereal',
          'fairycore',
          'fairy_grunge',
          'fantasy',
          'kinderwhore',
          'medieval_fantasy',
          'mythpunk',
          'renaissance_revival',
          'twilightcore',
          'whimsigothic',
          'y2k',
        ],
      },
      mediaCulture: {
        media: [
          "A Knight's Tale (2001)",
          'The Mists of Avalon (2001)',
          'Ella Enchanted (2004)',
          'Robin Hood (2006-2009)',
          'Merlin (2008-2012)',
        ],
        brands: ['Anna Sui  Betsey Johnson   Jean Paul Gautier   Versace'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Four_Colors',
    name: 'Four Colors',
    id: 'four_colors',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/7/75/IPod_promotional_campaign_2003.jpeg',
    description:
      'Four Colors was a frequently used color scheme found in consumer products and consumer technology during the Mid-2000s to the Mid-2010s, first primarily seen around 2004 as a part of Apples iPod "Silhouette" advertising campaign. It is a subgenre of Superflat Pop and Frutiger Aero and prominently consists of the colors electric lime, sky blue, hot pink and neon orange. This color palette and the visuals of the aesthetic overlaps with Bright Tertiaries, which uses tertiary colors like teal, lime green, and orange or fuchsia, as well as flat humanist designs. Four Colors is popular in Japan with stores and brands such as Daiso, Sony and Fujifilm.',
    categories: ['consumer_aesthetics', 'design_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['21th_century', '2000s'],
      },
      visualThemes: {
        colours: ['Electric lime', 'sky blue', 'hot pink', 'neon orange (Primary)Others (Accents)'],
        values: ['Personalization'],
      },
      connections: {
        related: [
          'bright_tertiaries',
          'dollar_store_vernacular',
          'figuration_narrative',
          'flat_design',
          'frutiger_aero',
          'mc',
          'bling',
          'old_web',
          'pop_art',
          'superflat_pop',
          'technozen',
          'ur',
          'bling',
          'vectordelia',
        ],
      },
      mediaCulture: {
        media: ['i', 'Pod promotional poster'],
        brands: ['Apple', 'Sony', 'Nintendo', 'Most Japanese consumer brands'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/McBling',
    name: 'McBling',
    id: 'mcbling',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/d/d0/Mcbling_moodb.png',
    description:
      'McBling is a fashion and lifestyle aesthetic that was prominent from roughly 2000 to 2008,[1] overlapping with Y2K Futurism, Frutiger Aero, Scene, and UrBling. It was succeeded by Recession Pop and Indie Sleaze. The term was coined by Froyo Tam of the Consumer Aesthetics Research Institute (CARI). Although frequently mistakenly referred to as "Y2K," McBling is a distinct aesthetic that swapped Y2K\'s futuristic look for a grounded, yet equally extravagant, style heavily influenced by hip-hop fashion and the rise of reality television. The look was characterized by a maximalist philosophy of "trashy" glamour, including iconic items such as Juicy Couture velour tracksuits, Von Dutch trucker hats, low-rise jeans, and an abundance of rhinestones, glitter, and visible luxury logos. The aesthetic is closely related to the celebrity tabloid culture of the mid-2000s, best represented by figures like Paris Hilton, Lindsay Lohan, and Britney Spears.',
    categories: ['consumer_aesthetics', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Trashy Y2K', 'Glam Y2K', '2000s Glam', '2000s Trashy'],
        decade: ['21th_century', '2000s'],
        location: ['United States'],
      },
      visualThemes: {
        motifs: [
          'Rhinestones',
          'glitter',
          'Juicy Couture tracksuits',
          'Von Dutch trucker hats',
          'low-rise jeans',
          'visible thongs',
          'flip phones',
          'paparazzi photos',
          'tabloid culture',
        ],
        colours: ['Hot pink', 'baby pink', 'metallics (gold and silver)', 'black', 'white'],
        values: ['Celebrity', 'fame', 'luxury', 'consumerism', '"new money" attitude', 'partying', '"trashy" glamour'],
      },
      connections: {
        related: [
          'baddie',
          'barbiecore',
          'bimbocore',
          'bro_hoe',
          'bubblegum_bitch',
          'bubblegum_bling_revivalfjortis',
          'frutiger_aero',
          'groovival',
          'millennium_disco',
          'guido',
          'indie_sleaze',
          'recession_pop',
          'scene',
          'surf_crush',
          'trailer_park_princess',
          'tweencore',
          'ur',
          'bling',
          'y2k_futurism',
        ],
      },
      mediaCulture: {
        platform: ['My', 'Space', 'Perez Hilton (blog)'],
        media: ['The Simple Life', 'Mean Girls', 'Laguna Beach', 'Bling Era Rap Videos'],
        brands: ['Juicy Couture', 'Von Dutch', 'Louis Vuitton', 'Dior', 'Playboy', 'Bebe', 'Baby Phat'],
        figures: ['Paris Hilton', 'Lindsay Lohan', 'Britney Spears', 'Nicole Richie', 'Jessica Simpson'],
      },
      timeline: {
        preceded: ['grunge', 'heroin_chic', 'memphis_lite'],
        succeeded: ['recession_pop', 'swag', 'indie_sleaze'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Metalheart',
    name: 'Metalheart',
    id: 'metalheart',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/b/b9/EeyQlyXXsAEEUps.jpg',
    description:
      'Metalheart emerged during the Y2K Futurism era of the late 1990s, replacing older Cyberpunk aesthetics such as Early Cyber and Cyberdelic. Websites dated back to that period such as 2Advanced studios and DeviantArt influenced the aesthetic, possibly following the success of The Matrix. Metalheart was named after Andreas Lindholm and Anders F. Rönnblom\'s 2001 book of the same title. This aesthetic peaked in popularity in the Early 2000s and later became oversaturated by the Mid 2000s. After that, it was morphed into McBling/Vectordelia/UrBling vector graphics and was replaced by Hipness Purgatory. The visuals consist of deformed abstract shapes, that can be either 3D metallic with bead blast and chrome textures or 2D with geometric flat shapes, as well as futurist UIs, that contain minimalist iconography, abstract lines and lights, grids, coding text, and futuristic fonts. These visual elements are usually seen alongside a blurry dark background. It can be said that Metalheart is a darker and "edgier" offshoot of the Y2K Futurism aesthetic with a more abstract and mechanical feeling to it.',
    categories: ['consumer_aesthetics', 'design_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Depthcore', 'Trendwhore'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: ['Deformed abstract shapes', 'metal/chrome textures', 'futuristic UI and fonts'],
        colours: ['Gray', 'Black', 'White', 'Blue', 'Green', 'Red', 'Yellow'],
      },
      connections: {
        related: [
          'abstract_tech',
          'early_cyber',
          'cyberdelic',
          'cybersigilism',
          'chromecore',
          'corporate_grunge',
          'cyberpunk',
          'dark_aero',
          'gen_x_soft_club90s_cool',
          'hexatron',
          'hipness_purgatory',
          'mc',
          'bling',
          'med-tech_visions',
          'nu-metal',
          'silicon_dreams',
          'ur',
          'bling',
          'vectorbloom',
          'vectorheart',
          'webcorey2k_futurism',
        ],
      },
      mediaCulture: {
        media: ['The Matrix'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/UrBling',
    name: 'UrBling',
    id: 'urbling',
    imageUrl:
      'https://static.wikia.nocookie.net/aesthetics/images/e/eb/Screenshot_of_the_Jason_Siu_and_Co._website_2.jpeg',
    description:
      'The aesthetic is characterized mainly by visuals from the early to late 2000s and is described as a form of "Urban-McBling." It shares maximalist and visually excessive elements similar to McBling but is less focused on bling. Key visual motifs include silhouetted streetlights, power lines, buildings, highways, and grungy effects. Other recognizable features are wings, crests, flames, tribal tattoo-like motifs, paint splatters and drips, and colors that tend toward sepia tones with reds, yellows, and oranges, alongside blacks and greys. Typography and graphic styles within Urbling include slab sans-serifs, graffiti and stencil motifs, and gothic fonts. The overall effect has a grungy, urban feel, with influences drawn from "Kustom Kulture." It carries a masculinized aspect compared to the more bling-heavy McBling, reinforcing certain gender roles in its marketing and cultural presentation at the time.[2][3] UrBling was the aesthetic of choice for many popular AAA or AA games in the 2000s.',
    categories: ['consumer_aesthetics', 'design_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Urban Grunge', 'City Grunge'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'Silhouetted streetlights',
          'power lines',
          'buildings',
          'highways',
          'grungy effects',
          'wings',
          'crests',
          'flames',
          'tribal tattoo-looking motifs',
          'paint splatters/drips',
          'slab sans-serifs',
          'graffiti and stencil motifs & fonts',
          'gothic fonts',
        ],
        colours: ['Orange', 'red', 'yellow', 'black', 'white', 'silver'],
      },
      connections: {
        related: [
          'corporate_grunge',
          'cyber_grunge',
          'gangsta_rap',
          'graffiti_pop',
          'hip-hop',
          'mc',
          'bling',
          'metalheart',
          'neo-tribal',
          'nu-metal',
          'olderbrothercore',
          'post-grunge_maximalism',
          'scene',
          'shibuya_punk',
          'skater',
          'teenpunk',
          'vectordelia',
          'y2k_futurism',
        ],
      },
      mediaCulture: {
        media: ['Def Jam Recordings'],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Vectorheart',
    name: 'Vectorheart',
    id: 'vectorheart',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/d/db/Incubation_Time_Controlled_Fusion.jpg',
    description:
      'The Wipeout series, in which the Designers Republic was involved with for the first three games, is commonly associated with Vectorheart and thus the aesthetic is also occassionally known as Wipeout Design.[2] The exact origin of the Vectorheart aesthetic is hard to define, but pioneers of the style include design firms such as Bionic Systems and The Designers Republic.[1] Vectorheart began to appear in the Late-1990s, often associated with Y2K Futurism due to its sleek, cutting edge style. This style complimented the futurism that Y2K Futurism promoted, leading to a lot of overlap between the two. Vectorheart also strongly resembles Gen X Soft Club, another Y2K subgenre, incorporating the same abstract flourishes and design philosophy. Vectorheart maintained its popularity into the Early-2000s, and the into the Mid-2000s. During the Mid-2000s, other adjacent aesthetics such a Y2K Futurism began to fall into decline. Despite this, Vectorheart maintained its popularity into the 2010s, being popular alongside aesthetics like Vectordelia and Vectorflourish. During this time, Vectorheart was used for purposes like advertising, art, web design, magazine covers, and more.',
    categories: ['consumer_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        decade: ['20th_century', '1990s'],
        creator: ['The Designers Republic'],
      },
      visualThemes: {
        motifs: [
          'Striking vector shapes',
          '45- and/or 60-degree diagonal lines',
          'futuristic and/or experimental typography',
          'flat colors',
          'high-contrast colors',
          'maximalist-minimalism',
          'silhouettes',
          'icons',
          'occasional references to Japanese culture',
          'occasional criticism of capitalism and consumerism rooted in irony',
        ],
      },
      connections: {
        related: [
          'abstract_tech',
          'acid_design',
          'cyberpunk',
          'flat_design',
          'gen_x_soft_club',
          'hexatron',
          'international_typographic_style',
          'metalheart',
          'neo-vectorheart',
          'old_web',
          'racing',
          'superflat_pop',
          'supergraphic_ultramodern',
          'urbancore',
          'vectordelia',
          'vectorflourishy2k_futurism',
        ],
      },
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Webcore',
    name: 'Webcore',
    id: 'webcore',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/2/28/WebcoreAesthetic.jpg',
    description:
      'The aesthetic is predicated on the appropriation of obsolete internet artifacts, such as GeoCities-era .GIFs, high-contrast browser windows or pop-ups, and system-level error dialogues. Although it draws from historical sources (particularly the Old Web), Webcore functions as a surrealist deconstruction, placing these nostalgic motifs into abstract voids or dreamlike contexts. Webcore developed as a reaction to the highly curated, centralized, and corporate nature of the modern internet (Web 2.0). Its ethos is a nostalgic yearning for the perceived freedom and amateur creativity of the early "Wild West" era of the web, before it was dominated by a few large social media platforms and algorithmic content feeds. The aesthetic romanticizes the period\'s "utopian vision" of the internet as a decentralized space for individual expression. While elements of this nostalgia were present in earlier aesthetics like Vaporwave, Webcore was significantly popularized and codified by the viral success of the animated YouTube series ENA by Peruvian animator Joel G., which premiered in May 2020. The series\' unique visual style, which combines simple 3D models, clunky animations, and browser-window interfaces with a surreal and often unsettling narrative, became a major touchstone for the aesthetic and its community.',
    categories: ['internet_aesthetics'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Internetcore', 'Enacore'],
        decade: ['21th_century', '2010s', '2020s'],
      },
      visualThemes: {
        motifs: [
          'Nostalgic internet imagery (Geo',
          'Cities',
          'Windows XP)',
          'pixel art',
          'early 3D graphics',
          'browser windows',
          'surrealism',
          'pop-ups',
          'error messages',
          'outdated technology',
        ],
        colours: ['Bright primary colors', 'often with digital distortion or pastel filters'],
        values: [
          'Nostalgia (anemoia)',
          'critique of the modern corporate internet',
          'digital surrealism',
          'creativity',
        ],
      },
      connections: {
        related: [
          '2010s_meme_maximalism',
          'cybercore',
          'demoscene',
          'dreamcore',
          'frutiger_aero',
          'glitch_art',
          'glitchcore',
          'old_web',
          'silicon_dreams',
          'techno',
          'neko2000vaporwave',
          'weirdcore',
          'xpiritualism',
          'y2k_futurism',
          'yabujincore',
        ],
      },
      mediaCulture: {
        platform: ['You', 'Tube', 'Tik', 'Tok', 'Sound', 'Cloud'],
        figures: ['Joel G. (ENA)', 'Graham Kartna', 'Oliver Buckland'],
      },
      timeline: {
        preceded: ['vaporwave'],
      },
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Y2K',
    name: 'Y2K',
    id: 'y2k',
    imageUrl: '',
    description:
      'Y2K is a retrospective term for the cultural period and zeitgeist that existed from approximately the late 1990s to the early 2000s. The name is derived from the Year 2000 problem, a widespread computer programming issue that created a cultural focal point of both anxiety and optimism about the new millennium. While the term "Y2K" is now used colloquially on social media to describe a wide range of 2000s trends, it originally referred to a more specific futuristic style. This page serves as a historical overview of the era and a hub for the various aesthetics that flourished within it.',
    categories: [],
    isVisible: true,
    metadata: {
      connections: {},
      origins: {},
      timeline: {},
    },
  },
  {
    url: 'https://aesthetics.fandom.com/wiki/Y2K_Futurism',
    name: 'Y2K Futurism',
    id: 'y2k_futurism',
    imageUrl: 'https://static.wikia.nocookie.net/aesthetics/images/0/09/Y2k_moodb.png',
    description:
      'The visual style of Y2K Futurism is characterized by its heavy use of computer-generated imagery, which was rapidly advancing at the time. Common motifs include abstract 3D graphics, often with shiny, liquid-like metallic textures, and organic, blobby shapes sometimes referred to as "blobitecture". Product and hardware design from the era embraced translucency and bright colors, exemplified by Apple\'s iMac G3. The color palette was typically cool-toned, dominated by icy blues, silver, and glossy white, often punctuated by sharp accents of lime green or orange. This visual style was ubiquitous in the graphic design, music videos, and video game interfaces of the period. The term "Y2K aesthetic" was originally coined by Evan Collins of the Consumer Aesthetics Research Institute to describe this specific futuristic style, named after the Year 2000 problem. However, in the 2020s revival, the term "Y2K" was broadened on social media to refer to all trends of the early 2000s. As a result, the more precise "Y2K Futurism" is now used to distinguish this particular aesthetic from the wider cultural zeitgeist of the era, which is covered on the main Y2K overview page. Y2K Futurism has its origins in the underground UK rave scene of the Late-1980s/Early-1990s. Rave flyers at this time featured designs that would later become known as the Y2K style, and artists released albums which would form the basis of Y2K-era electronica, i.e. The Prodigy\'s Experience (1992), Aphex Twin\'s Selected Ambient Works (recorded 1985–1992), and The Future Sound of London\'s Accelerator (1992). This period also saw the early works of the Sheffield-based Designers Republic, founded in 1986.',
    categories: ['architectural_styles', 'consumer_aesthetics', 'design_aesthetics', 'music', 'fashion'],
    isVisible: true,
    metadata: {
      origins: {
        otherNames: ['Y2K Aesthetic', 'Cyber Y2K', 'Kaybug'],
        decade: ['20th_century', '1990s'],
      },
      visualThemes: {
        motifs: [
          'Abstract 3D graphics ("blobs")',
          'translucent or transparent materials',
          'metallic textures',
          'chrome',
          'sleek typography',
          'futuristic interfaces',
        ],
        colours: [
          'Cool-toned palettes',
          'icy blue',
          'silver',
          'glossy white',
          'black',
          'with accents of bright orange and lime green',
        ],
        values: ['Techno-utopianism', 'optimism for the new millennium', 'digital futurism', 'sleek minimalism'],
      },
      connections: {
        related: [
          '90s_cool',
          'abstract_tech',
          'bubblegum_dance',
          'chromecore',
          'corporate_grunge',
          'cybercore_reinterpretationcyberpunk',
          'dorfic',
          'frutiger_aero',
          'millennium_disco',
          'gen_x_soft_club',
          'low_poly',
          'groovival',
          'mc',
          'bling',
          'metalheart',
          'neo-y2k_revivalretrofuturism',
          'seapunk',
          'shibuya_punk',
          'superflat_pop',
          'vectorheart',
        ],
      },
      mediaCulture: {
        media: ['The Matrix', 'Space Channel 5', 'Wipeout', 'Jet Set Radio', 'Toonami'],
        brands: ['Apple (i', 'Mac G3)', 'Nokia', 'Oakley', 'Sega', 'Sony', 'Play', 'Station'],
        figures: [
          'TLC',
          'Britney Spears',
          'Hype Williams',
          'The Designers Republic',
          'Jony Ive',
          'Janet Jackson',
          'Daft Punk',
          'The Wachowskis',
          'Björk',
        ],
      },
      timeline: {
        preceded: ['cassette_futurism', 'grunge', 'memphis_lite', 'early_cyber', 'factory_pomo'],
        succeeded: ['frutiger_aero'],
      },
    },
  },
];
